[[bin]]
name = "staging-staking-miner"
path = "src/main.rs"

[package]
name = "staging-staking-miner"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
clap = { version = "4.4.1", features = ["derive", "env"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
jsonrpsee = { version = "0.16.2", features = ["ws-client", "macros"] }
log = "0.4.17"
paste = "1.0.7"
serde = "1.0.188"
serde_json = "1.0"
thiserror = "1.0.31"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread", "sync"] }
remote-externalities = { package = "frame-remote-externalities" , path = "../../../substrate/utils/frame/remote-externalities" }
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }
sp-core = { path = "../../../substrate/primitives/core" }
sp-version = { path = "../../../substrate/primitives/version" }
sp-state-machine = { path = "../../../substrate/primitives/state-machine" }
sp-runtime = { path = "../../../substrate/primitives/runtime" }
sp-npos-elections = { path = "../../../substrate/primitives/npos-elections" }
sc-transaction-pool-api = { path = "../../../substrate/client/transaction-pool/api" }

frame-system = { path = "../../../substrate/frame/system" }
frame-support = { path = "../../../substrate/frame/support" }
frame-election-provider-support = { path = "../../../substrate/frame/election-provider-support" }
pallet-election-provider-multi-phase = { path = "../../../substrate/frame/election-provider-multi-phase" }
pallet-staking = { path = "../../../substrate/frame/staking" }
pallet-balances = { path = "../../../substrate/frame/balances" }
pallet-transaction-payment = { path = "../../../substrate/frame/transaction-payment" }

core-primitives = { package = "polkadot-core-primitives", path = "../../core-primitives" }

runtime-common = { package = "polkadot-runtime-common", path = "../../runtime/common" }
polkadot-runtime = { path = "../../runtime/polkadot" }
kusama-runtime = { package = "staging-kusama-runtime", path = "../../runtime/kusama" }
westend-runtime = { path = "../../runtime/westend" }
exitcode = "1.1"

sub-tokens = { git = "https://github.com/paritytech/substrate-debug-kit", branch = "master" }
signal-hook = "0.3"
futures-util = "0.3"

[dev-dependencies]
assert_cmd = "2.0.4"

[features]
runtime-benchmarks = [
	"core-primitives/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"kusama-runtime/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-election-provider-multi-phase/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
	"polkadot-runtime/runtime-benchmarks",
	"remote-externalities/runtime-benchmarks",
	"runtime-common/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-npos-elections/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"sp-version/runtime-benchmarks",
	"westend-runtime/runtime-benchmarks",
]
