[[bin]]
name = "staging-staking-miner"
path = "src/main.rs"

[package]
name = "staging-staking-miner"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "staging-staking-miner"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
clap = { version = "4.4.2", features = ["derive", "env"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
jsonrpsee = { version = "0.16.2", features = ["ws-client", "macros"] }
log = "0.4.17"
paste = "1.0.7"
serde = "1.0.188"
serde_json = "1.0"
thiserror = "1.0.48"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread", "sync"] }
remote-externalities = { package = "frame-remote-externalities", path = "../../../substrate/utils/frame/remote-externalities", version = "0.30.0" }
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }
sp-core = { version = "23.0.0", path = "../../../substrate/primitives/core" }
sp-version = { version = "24.0.0", path = "../../../substrate/primitives/version" }
sp-state-machine = { version = "0.30.0", path = "../../../substrate/primitives/state-machine" }
sp-runtime = { version = "26.0.0", path = "../../../substrate/primitives/runtime" }
sp-npos-elections = { version = "21.0.0", path = "../../../substrate/primitives/npos-elections" }
sc-transaction-pool-api = { version = "23.0.0", path = "../../../substrate/client/transaction-pool/api" }
frame-system = { version = "23.0.0", path = "../../../substrate/frame/system" }
frame-support = { version = "23.0.0", path = "../../../substrate/frame/support" }
frame-election-provider-support = { version = "23.0.0", path = "../../../substrate/frame/election-provider-support" }
pallet-election-provider-multi-phase = { version = "22.0.0", path = "../../../substrate/frame/election-provider-multi-phase" }
pallet-staking = { version = "23.0.0", path = "../../../substrate/frame/staking" }
pallet-balances = { version = "23.0.0", path = "../../../substrate/frame/balances" }
pallet-transaction-payment = { version = "23.0.0", path = "../../../substrate/frame/transaction-payment" }

core-primitives = { package = "polkadot-core-primitives", path = "../../core-primitives", version = "2.0.0" }

runtime-common = { package = "polkadot-runtime-common", path = "../../runtime/common", version = "2.0.0" }
polkadot-runtime = { version = "2.0.0", path = "../../runtime/polkadot" }
kusama-runtime = { package = "staging-kusama-runtime", path = "../../runtime/kusama", version = "2.0.0" }
westend-runtime = { version = "2.0.0", path = "../../runtime/westend" }
exitcode = "1.1"

sub-tokens = { git = "https://github.com/paritytech/substrate-debug-kit", branch = "master" }
signal-hook = "0.3"
futures-util = "0.3"

[dev-dependencies]
assert_cmd = "2.0.4"
