[package]
name = "sc-sync-state-rpc"
version = "0.10.0-dev"
authors.workspace = true
description = "A RPC handler to create sync states for light clients."
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.85"
thiserror = "1.0.30"
sc-chain-spec = { path = "../chain-spec" }
sc-client-api = { path = "../api" }
sc-consensus-babe = { path = "../consensus/babe" }
sc-consensus-epochs = { path = "../consensus/epochs" }
sc-consensus-grandpa = { path = "../consensus/grandpa" }
sp-blockchain = { path = "../../primitives/blockchain" }
sp-runtime = { path = "../../primitives/runtime" }

[features]
runtime-benchmarks = [
	"sc-chain-spec/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus-babe/runtime-benchmarks",
	"sc-consensus-epochs/runtime-benchmarks",
	"sc-consensus-grandpa/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
