[package]
name = "sc-consensus-manual-seal"
version = "0.10.0-dev"
authors.workspace = true
description = "Manual sealing engine for Substrate"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
assert_matches = "1.3.0"
async-trait = "0.1.57"
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.21"
futures-timer = "3.0.1"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus" }
sc-client-api = { path = "../../api" }
sc-consensus = { path = "../common" }
sc-consensus-aura = { path = "../aura" }
sc-consensus-babe = { path = "../babe" }
sc-consensus-epochs = { path = "../epochs" }
sc-transaction-pool = { path = "../../transaction-pool" }
sc-transaction-pool-api = { path = "../../transaction-pool/api" }
sp-api = { path = "../../../primitives/api" }
sp-blockchain = { path = "../../../primitives/blockchain" }
sp-consensus = { path = "../../../primitives/consensus/common" }
sp-consensus-aura = { path = "../../../primitives/consensus/aura" }
sp-consensus-babe = { path = "../../../primitives/consensus/babe" }
sp-consensus-slots = { path = "../../../primitives/consensus/slots" }
sp-core = { path = "../../../primitives/core" }
sp-inherents = { path = "../../../primitives/inherents" }
sp-keystore = { path = "../../../primitives/keystore" }
sp-runtime = { path = "../../../primitives/runtime" }
sp-timestamp = { path = "../../../primitives/timestamp" }

[dev-dependencies]
tokio = { version = "1.22.0", features = ["rt-multi-thread", "macros"] }
sc-basic-authorship = { path = "../../basic-authorship" }
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }
substrate-test-runtime-transaction-pool = { path = "../../../test-utils/runtime/transaction-pool" }

[features]
runtime-benchmarks = [
	"sc-basic-authorship/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus-aura/runtime-benchmarks",
	"sc-consensus-babe/runtime-benchmarks",
	"sc-consensus-epochs/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sc-transaction-pool/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus-aura/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-consensus-slots/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-timestamp/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
	"substrate-test-runtime-transaction-pool/runtime-benchmarks",
]
