[package]
name = "pallet-example-storage-migrations"
version = "4.0.0-dev"
authors.workspace = true
edition.workspace = true
license = "MIT-0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME example pallet demonstrating best-practices for writing storage migrations."

[lib]
doctest = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
docify = "0.2.2"
log = { version = "0.4.20", default-features = false }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
frame-support = { path = "../../support", default-features = false}
frame-executive = { path = "../../executive", default-features = false}
frame-system = { path = "../../system", default-features = false}
frame-try-runtime = { path = "../../try-runtime", default-features = false, optional = true}
pallet-balances = { path = "../../balances", default-features = false}
sp-std = { path = "../../../primitives/std", default-features = false}
sp-runtime = { path = "../../../primitives/runtime" }
sp-core = { path = "../../../primitives/core" }
sp-io = { path = "../../../primitives/io" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"frame-try-runtime/std",
	"pallet-balances/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime/try-runtime",
	"pallet-balances/try-runtime",
	"sp-runtime/try-runtime",
]
