# 🔒 PROTECTED: Changes to locks-review-team should be approved by the current locks-review-team
locks-review-team: locks-review
team-leads-team: polkadot-review
action-review-team: ci

rules:
  - name: CI files
    check_type: changed_files
    condition:
      include: ^\.gitlab-ci\.yml|^docker/.*|^\.github/.*|^\.gitlab/.*|^\.config/nextest.toml|^\.cargo/.*
      exclude: ^\.gitlab/pipeline/zombienet.*
    min_approvals: 2
    teams:
      - ci
      - release-engineering

  - name: Core developers
    check_type: changed_files
    condition:
      include: .*
      # excluding files from 'Runtime files {relay, system para}' and 'CI files' rules
      exclude: ^polkadot/runtime/(kusama|polkadot)/src/[^/]+\.rs$|^cumulus/parachains/runtimes/assets/(asset-hub-kusama|asset-hub-polkadot)/src/[^/]+\.rs$|^cumulus/parachains/runtimes/bridge-hubs/(bridge-hub-kusama|bridge-hub-polkadot)/src/[^/]+\.rs$|^cumulus/parachains/runtimes/collectives/collectives-polkadot/src/[^/]+\.rs$|^cumulus/parachains/common/src/[^/]+\.rs$|^substrate/frame/(?!.*(nfts/.*|uniques/.*|babe/.*|grandpa/.*|beefy|merkle-mountain-range/.*|contracts/.*|election|nomination-pools/.*|staking/.*|aura/.*))|^\.gitlab-ci\.yml|^docker/.*|^\.github/.*|^\.gitlab/.*|^\.config/nextest.toml|^\.cargo/.*
    min_approvals: 2
    teams:
      - core-devs

  # Relays
  - name: Runtime files relay chains
    check_type: changed_files
    condition: ^polkadot/runtime/(kusama|polkadot)/src/[^/]+\.rs$
    all_distinct:
      - min_approvals: 1
        teams:
          - locks-review
      - min_approvals: 1
        teams:
          - polkadot-review

  # System Parachains
  - name: Runtime files system parachains
    check_type: changed_files
    condition: ^cumulus/parachains/runtimes/assets/(asset-hub-kusama|asset-hub-polkadot)/src/[^/]+\.rs$|^cumulus/parachains/runtimes/bridge-hubs/(bridge-hub-kusama|bridge-hub-polkadot)/src/[^/]+\.rs$|^cumulus/parachains/runtimes/collectives/collectives-polkadot/src/[^/]+\.rs$|^cumulus/parachains/common/src/[^/]+\.rs$
    all_distinct:
      - min_approvals: 1
        teams:
          - locks-review
      - min_approvals: 1
        teams:
          - polkadot-review

  # if there are any changes in the bridges subtree (in case of backport changes back to bridges repo)
  - name: Bridges subtree files
    check_type: changed_files
    condition: ^bridges/.*
    min_approvals: 1
    teams:
      - bridges-core

  # frame
  - name: FRAME coders substrate
    check_type: changed_files
    condition:
      include: ^substrate/frame/(?!.*(nfts/.*|uniques/.*|babe/.*|grandpa/.*|beefy|merkle-mountain-range/.*|contracts/.*|election|nomination-pools/.*|staking/.*|aura/.*))
    all:
      - min_approvals: 2
        teams:
          - core-devs
      - min_approvals: 1
        teams:
          - frame-coders

prevent-review-request:
  teams:
    - core-devs
