[package]
name = "node-testing"
version = "3.0.0-dev"
authors.workspace = true
description = "Test utilities for Substrate node."
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
fs_extra = "1"
futures = "0.3.21"
log = "0.4.17"
tempfile = "3.1.0"
frame-system = { path = "../../../frame/system" }
node-executor = { path = "../executor" }
node-primitives = { path = "../primitives" }
kitchensink-runtime = { path = "../runtime" }
pallet-asset-conversion = { path = "../../../frame/asset-conversion" }
pallet-assets = { path = "../../../frame/assets" }
pallet-asset-conversion-tx-payment = { path = "../../../frame/transaction-payment/asset-conversion-tx-payment" }
pallet-asset-tx-payment = { path = "../../../frame/transaction-payment/asset-tx-payment" }
sc-block-builder = { path = "../../../client/block-builder" }
sc-client-api = { path = "../../../client/api" }
sc-client-db = { path = "../../../client/db", features = ["rocksdb"]}
sc-consensus = { path = "../../../client/consensus/common" }
sc-executor = { path = "../../../client/executor" }
sc-service = { path = "../../../client/service", features = [
	"test-helpers",
	"rocksdb",
]}
sp-api = { path = "../../../primitives/api" }
sp-block-builder = { path = "../../../primitives/block-builder" }
sp-blockchain = { path = "../../../primitives/blockchain" }
sp-consensus = { path = "../../../primitives/consensus/common" }
sp-core = { path = "../../../primitives/core" }
sp-inherents = { path = "../../../primitives/inherents" }
sp-io = { path = "../../../primitives/io" }
sp-keyring = { path = "../../../primitives/keyring" }
sp-runtime = { path = "../../../primitives/runtime" }
sp-timestamp = { path = "../../../primitives/timestamp", default-features = false}
substrate-test-client = { path = "../../../test-utils/client" }

[features]
runtime-benchmarks = [
	"frame-system/runtime-benchmarks",
	"kitchensink-runtime/runtime-benchmarks",
	"node-executor/runtime-benchmarks",
	"node-primitives/runtime-benchmarks",
	"pallet-asset-conversion-tx-payment/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-asset-tx-payment/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"sc-block-builder/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-client-db/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-executor/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-timestamp/runtime-benchmarks",
	"substrate-test-client/runtime-benchmarks",
]
