[package]
authors.workspace = true
name = "cumulus-relay-chain-interface"
version = "0.1.0"
edition.workspace = true

[dependencies]
polkadot-overseer = { path = "../../../polkadot/node/overseer" }

cumulus-primitives-core = { path = "../../primitives/core" }

sp-api = { path = "../../../substrate/primitives/api" }
sp-blockchain = { path = "../../../substrate/primitives/blockchain" }
sp-state-machine = { path = "../../../substrate/primitives/state-machine" }
sc-client-api = { path = "../../../substrate/client/api" }

futures = "0.3.28"
async-trait = "0.1.73"
thiserror = "1.0.47"
jsonrpsee-core = "0.16.2"
parity-scale-codec = "3.6.4"

[features]
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"polkadot-overseer/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
]
