[package]
authors.workspace = true
name = "cumulus-relay-chain-interface"
version = "0.2.0"
edition.workspace = true
description = "cumulus-relay-chain-interface"

[dependencies]
polkadot-overseer = { version = "2.0.0", path = "../../../polkadot/node/overseer" }
cumulus-primitives-core = { version = "0.2.0", path = "../../primitives/core" }
sp-api = { version = "21.0.0", path = "../../../substrate/primitives/api" }
sp-blockchain = { version = "23.0.0", path = "../../../substrate/primitives/blockchain" }
sp-state-machine = { version = "0.30.0", path = "../../../substrate/primitives/state-machine" }
sc-client-api = { version = "23.0.0", path = "../../../substrate/client/api" }

futures = "0.3.28"
async-trait = "0.1.73"
thiserror = "1.0.48"
jsonrpsee-core = "0.16.2"
parity-scale-codec = "3.6.4"
