[settings]
node_spawn_timeout = 240

[relaychain]
default_command = "{{POLKADOT_BINARY_PATH}}"
default_args = [ "-lparachain=debug,xcm=trace" ]
chain = "kusama-local"

	[[relaychain.nodes]]
	name = "alice-kusama-validator"
	validator = true
	rpc_port = 9932
	ws_port = 9942
	balance = 200000000000000

	[[relaychain.nodes]]
	name = "bob-kusama-validator"
	validator = true
	rpc_port = 9933
	ws_port = 9943
	balance = 200000000000000

	[[relaychain.nodes]]
	name = "charlie-kusama-validator"
	validator = true
	rpc_port = 9934
	ws_port = 9944
	balance = 200000000000000

[[parachains]]
id = 1002
chain = "bridge-hub-kusama-local"
cumulus_based = true

	# run alice as parachain collator
	[[parachains.collators]]
	name = "bridge-hub-kusama-collator1"
	validator = true
	command = "{{POLKADOT_PARACHAIN_BINARY_PATH}}"
	rpc_port = 8933
	ws_port = 8943
	args = [
		"-lparachain=debug,runtime::bridge-hub=trace,runtime::bridge=trace,runtime::bridge-dispatch=trace,bridge=trace,runtime::bridge-messages=trace,xcm=trace",
		"--force-authoring",
		"--", "--port 41333", "--rpc-port 48933", "--ws-port 48943"
	]

	# run bob as parachain collator
	[[parachains.collators]]
	name = "bridge-hub-kusama-collator2"
	validator = true
	command = "{{POLKADOT_PARACHAIN_BINARY_PATH}}"
	rpc_port = 8934
	ws_port = 8944
	args = [
		"-lparachain=trace,runtime::bridge-hub=trace,runtime::bridge=trace,runtime::bridge-dispatch=trace,bridge=trace,runtime::bridge-messages=trace,xcm=trace",
		"--force-authoring",
		"--", "--port 41334", "--rpc-port 48934", "--ws-port 48944"
	]

[[parachains]]
id = 1000
chain = "asset-hub-kusama-local"
cumulus_based = true

	[[parachains.collators]]
	name = "asset-hub-kusama-collator1"
	rpc_port = 9911
	ws_port = 9910
	command = "{{POLKADOT_PARACHAIN_BINARY_PATH_FOR_ASSET_HUB_KUSAMA}}"
	args = [
		"-lparachain=debug,xcm=trace,runtime::bridge-transfer=trace",
		"--", "--port 51333", "--rpc-port 58933", "--ws-port 58943"
	]

	[[parachains.collators]]
	name = "asset-hub-kusama-collator2"
	command = "{{POLKADOT_PARACHAIN_BINARY_PATH_FOR_ASSET_HUB_KUSAMA}}"
	args = [
		"-lparachain=debug,xcm=trace,runtime::bridge-transfer=trace",
	]
	extra_args = [
		"--no-mdns", "--bootnodes {{'asset-hub-kusama-collator1'|zombie('multiAddress')}}",
		"--", "--port 51433", "--rpc-port 58833", "--ws-port 58843"
	]

#[[hrmp_channels]]
#sender = 1000
#recipient = 1002
#max_capacity = 4
#max_message_size = 524288
#
#[[hrmp_channels]]
#sender = 1002
#recipient = 1000
#max_capacity = 4
#max_message_size = 524288
