[package]
name = "sc-consensus-grandpa"
version = "0.10.0-dev"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Integration of the GRANDPA finality gadget into substrate."
documentation = "https://docs.rs/sc-consensus-grandpa"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ahash = "0.8.2"
array-bytes = "6.1"
async-trait = "0.1.57"
dyn-clone = "1.0"
finality-grandpa = { version = "0.16.2", features = ["derive-codec"] }
futures = "0.3.21"
futures-timer = "3.0.1"
log = "0.4.17"
parity-scale-codec = { version = "3.6.1", features = ["derive"] }
parking_lot = "0.12.1"
rand = "0.8.5"
serde_json = "1.0.85"
thiserror = "1.0"
fork-tree = { path = "../../../utils/fork-tree" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus" }
sc-block-builder = { path = "../../block-builder" }
sc-chain-spec = { path = "../../chain-spec" }
sc-client-api = { path = "../../api" }
sc-transaction-pool-api = { path = "../../transaction-pool/api" }
sc-consensus = { path = "../common" }
sc-network = { path = "../../network" }
sc-network-gossip = { path = "../../network-gossip" }
sc-network-common = { path = "../../network/common" }
sc-telemetry = { path = "../../telemetry" }
sc-utils = { path = "../../utils" }
sp-api = { path = "../../../primitives/api" }
sp-application-crypto = { path = "../../../primitives/application-crypto" }
sp-arithmetic = { path = "../../../primitives/arithmetic" }
sp-blockchain = { path = "../../../primitives/blockchain" }
sp-consensus = { path = "../../../primitives/consensus/common" }
sp-core = { path = "../../../primitives/core" }
sp-consensus-grandpa = { path = "../../../primitives/consensus/grandpa" }
sp-keystore = { path = "../../../primitives/keystore" }
sp-runtime = { path = "../../../primitives/runtime" }

[dev-dependencies]
assert_matches = "1.3.0"
finality-grandpa = { version = "0.16.2", features = ["derive-codec", "test-helpers"] }
serde = "1.0.188"
tokio = "1.22.0"
sc-network = { path = "../../network" }
sc-network-test = { path = "../../network/test" }
sp-keyring = { path = "../../../primitives/keyring" }
sp-tracing = { path = "../../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }

[features]
runtime-benchmarks = [
	"sc-block-builder/runtime-benchmarks",
	"sc-chain-spec/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-network-common/runtime-benchmarks",
	"sc-network-gossip/runtime-benchmarks",
	"sc-network-test/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sc-telemetry/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sc-utils/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-arithmetic/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus-grandpa/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
]
