[package]
name = "bp-bridge-hub-cumulus"
description = "Primitives of BridgeHubRococo parachain runtime."
version = "0.2.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
# Bridge Dependencies

bp-polkadot-core = { path = "../polkadot-core", default-features = false, version = "0.2.0" }
bp-messages = { path = "../messages", default-features = false, version = "0.2.0" }
bp-runtime = { path = "../runtime", default-features = false, version = "0.2.0" }

# Substrate Based Dependencies

frame-system = { path = "../../../../substrate/frame/system", default-features = false, version = "23.0.0" }
frame-support = { path = "../../../../substrate/frame/support", default-features = false, version = "23.0.0" }
sp-api = { path = "../../../../substrate/primitives/api", default-features = false, version = "21.0.0" }
sp-std = { path = "../../../../substrate/primitives/std", default-features = false, version = "10.0.0" }

# Polkadot Dependencies
polkadot-primitives = { path = "../../../../polkadot/primitives", default-features = false, version = "2.0.0" }

[features]
default = [ "std" ]
std = [
	"bp-messages/std",
	"bp-polkadot-core/std",
	"bp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"polkadot-primitives/std",
	"sp-api/std",
	"sp-std/std",
]
