[package]
name = "node-template-runtime"
version = "0.1.0"
description = "A fresh FRAME-based Substrate node, ready for hacking."
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
homepage = "https://substrate.io/"
edition.workspace = true
license = "MIT-0"
publish = false
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }

pallet-aura = { path = "../../../frame/aura", default-features = false, version = "=23.0.0-dev.1" }
pallet-balances = { path = "../../../frame/balances", default-features = false, version = "=24.0.0-dev.1" }
frame-support = { path = "../../../frame/support", default-features = false, version = "=24.0.0-dev.1" }
pallet-grandpa = { path = "../../../frame/grandpa", default-features = false, version = "=24.0.0-dev.1" }
pallet-sudo = { path = "../../../frame/sudo", default-features = false, version = "=24.0.0-dev.1" }
frame-system = { path = "../../../frame/system", default-features = false, version = "=24.0.0-dev.1" }
frame-try-runtime = { path = "../../../frame/try-runtime", default-features = false, optional = true, version = "=0.30.0-dev.1" }
pallet-timestamp = { path = "../../../frame/timestamp", default-features = false, version = "=23.0.0-dev.1" }
pallet-transaction-payment = { path = "../../../frame/transaction-payment", default-features = false, version = "=24.0.0-dev.1" }
frame-executive = { path = "../../../frame/executive", default-features = false, version = "=24.0.0-dev.1" }
sp-api = { path = "../../../primitives/api", default-features = false, version = "=22.0.0-dev.1" }
sp-block-builder = { path = "../../../primitives/block-builder", default-features = false, version = "=22.0.0-dev.1" }
sp-consensus-aura = { path = "../../../primitives/consensus/aura", default-features = false, version = "=0.28.0-dev.1" }
sp-consensus-grandpa = { path = "../../../primitives/consensus/grandpa", default-features = false, version = "=9.0.0-dev.1" }
sp-core = { path = "../../../primitives/core", default-features = false, version = "=24.0.0-dev.1" }
sp-inherents = { path = "../../../primitives/inherents", default-features = false, version = "=22.0.0-dev.1" }
sp-offchain = { path = "../../../primitives/offchain", default-features = false, version = "=22.0.0-dev.1" }
sp-runtime = { path = "../../../primitives/runtime", default-features = false, version = "=27.0.0-dev.1" }
sp-session = { path = "../../../primitives/session", default-features = false, version = "=23.0.0-dev.1" }
sp-std = { path = "../../../primitives/std", default-features = false, version = "=11.0.0-dev.1" }
sp-storage = { path = "../../../primitives/storage", default-features = false, version = "=16.0.0-dev.1" }
sp-transaction-pool = { path = "../../../primitives/transaction-pool", default-features = false, version = "=22.0.0-dev.1" }
sp-version = { path = "../../../primitives/version", default-features = false, version = "=25.0.0-dev.1" }
sp-genesis-builder = { version = "=0.3.0-dev.1", default-features = false, path = "../../../primitives/genesis-builder" }

# Used for the node template's RPCs
frame-system-rpc-runtime-api = { path = "../../../frame/system/rpc/runtime-api", default-features = false, version = "=22.0.0-dev.1" }
pallet-transaction-payment-rpc-runtime-api = { path = "../../../frame/transaction-payment/rpc/runtime-api", default-features = false, version = "=24.0.0-dev.1" }

# Used for runtime benchmarking
frame-benchmarking = { path = "../../../frame/benchmarking", default-features = false, optional = true, version = "=24.0.0-dev.1" }
frame-system-benchmarking = { path = "../../../frame/system/benchmarking", default-features = false, optional = true, version = "=24.0.0-dev.1" }

# Local Dependencies
pallet-template = { path = "../pallets/template", default-features = false, version = "=0.1.0" }

[build-dependencies]
substrate-wasm-builder = { path = "../../../utils/wasm-builder", optional = true, version = "=13.0.0-dev.1" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-benchmarking?/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"frame-try-runtime?/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-sudo/std",
	"pallet-template/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"scale-info/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-consensus-grandpa/std",
	"sp-core/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-storage/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"substrate-wasm-builder",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-template/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-template/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"sp-runtime/try-runtime",
]
experimental = [ "pallet-aura/experimental" ]
