[package]
name = "cumulus-client-cli"
version = "0.3.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "cumulus-client-cli"

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0" }
url = "2.4.0"
sc-cli = { version = "=0.32.0-dev.1", path = "../../../substrate/client/cli" }
sc-client-api = { version = "=24.0.0-dev.1", path = "../../../substrate/client/api" }
sc-chain-spec = { version = "=23.0.0-dev.1", path = "../../../substrate/client/chain-spec" }
sc-service = { version = "=0.31.0-dev.1", path = "../../../substrate/client/service" }
sp-core = { version = "=24.0.0-dev.1", path = "../../../substrate/primitives/core" }
sp-runtime = { version = "=27.0.0-dev.1", path = "../../../substrate/primitives/runtime" }
