[package]
name = "xcm-simulator"
description = "Test kit to simulate cross-chain message passing and XCM execution"
version = "3.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
paste = "1.0.7"
frame-support = { version = "=24.0.0-dev.1", path = "../../../substrate/frame/support" }
sp-io = { version = "=26.0.0-dev.1", path = "../../../substrate/primitives/io" }
sp-std = { version = "=11.0.0-dev.1", path = "../../../substrate/primitives/std" }

xcm = { package = "staging-xcm", path = "..", version = "=3.0.0-dev.1" }
xcm-executor = { package = "staging-xcm-executor", path = "../xcm-executor", version = "=3.0.0-dev.1" }
xcm-builder = { package = "staging-xcm-builder", path = "../xcm-builder", version = "=3.0.0-dev.1" }
polkadot-core-primitives = { version = "=3.0.0-dev.1", path = "../../core-primitives" }
polkadot-parachain-primitives = { version = "=2.0.0-dev.1", path = "../../parachain" }
polkadot-runtime-parachains = { version = "=3.0.0-dev.1", path = "../../runtime/parachains" }
