[package]
name = "substrate-wasm-builder"
version = "5.0.0-dev"
authors.workspace = true
description = "Utility for building WASM binaries"
edition.workspace = true
readme = "README.md"
repository.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ansi_term = "0.12.1"
build-helper = "0.1.1"
cargo_metadata = "0.15.4"
strum = { version = "0.24.1", features = ["derive"] }
tempfile = "3.1.0"
toml = "0.7.3"
walkdir = "2.3.2"
sp-maybe-compressed-blob = { path = "../../primitives/maybe-compressed-blob" }
filetime = "0.2.16"
wasm-opt = "0.116"
parity-wasm = "0.45"
metadata-shortener = { git = "https://github.com/Alzymologist/metadata-shortener.git", optional = true }
sc-executor-wasmtime = { path = "../../client/executor/wasmtime", optional = true }
sp-io = { path = "../../primitives/io", optional = true }
frame-metadata = { version = "16.0.0", features = [ "current" ], optional = true }
codec = { package = "parity-scale-codec", version = "3.1.5", optional = true }
array-bytes = "6.1"
sp-tracing = { path = "../../primitives/tracing", optional = true }

[features]
default = [ "experimental-metadata-hash" ]
experimental-metadata-hash = [ "metadata-shortener", "sc-executor-wasmtime", "sp-io", "frame-metadata", "codec", "sp-tracing" ]
