[package]
name = "polkadot-node-subsystem-types"
description = "Subsystem traits and message definitions"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
derive_more = "0.99.17"
futures = "0.3.21"
polkadot-primitives = { version = "2.0.0", path = "../../primitives" }
polkadot-node-primitives = { version = "2.0.0", path = "../primitives" }
polkadot-node-network-protocol = { version = "2.0.0", path = "../network/protocol" }
polkadot-statement-table = { version = "2.0.0", path = "../../statement-table" }
polkadot-node-jaeger = { version = "2.0.0", path = "../jaeger" }
orchestra = "0.0.5"
sc-network = { version = "0.29.0", path = "../../../substrate/client/network" }
sp-api = { version = "21.0.0", path = "../../../substrate/primitives/api" }
sp-consensus-babe = { version = "0.27.0", path = "../../../substrate/primitives/consensus/babe" }
sp-authority-discovery = { version = "21.0.0", path = "../../../substrate/primitives/authority-discovery" }
sc-transaction-pool-api = { version = "23.0.0", path = "../../../substrate/client/transaction-pool/api" }
smallvec = "1.8.0"
substrate-prometheus-endpoint = { version = "0.14.0", path = "../../../substrate/utils/prometheus" }
thiserror = "1.0.48"
async-trait = "0.1.57"
