[package]
name = "xcm-procedural"
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "3.0.0-dev.1"
description = "xcm-procedural"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.28"
syn = "2.0.37"
Inflector = "0.11.4"
