[package]
name = "polkadot-rpc"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["server"] }
polkadot-primitives = { path = "../primitives" }
sc-client-api = { path = "../../substrate/client/api" }
sp-blockchain = { path = "../../substrate/primitives/blockchain" }
sp-keystore = { path = "../../substrate/primitives/keystore" }
sp-runtime = { path = "../../substrate/primitives/runtime" }
sp-api = { path = "../../substrate/primitives/api" }
sp-consensus = { path = "../../substrate/primitives/consensus/common" }
sp-consensus-babe = { path = "../../substrate/primitives/consensus/babe" }
sc-chain-spec = { path = "../../substrate/client/chain-spec" }
sc-rpc = { path = "../../substrate/client/rpc" }
sc-consensus-babe = { path = "../../substrate/client/consensus/babe" }
sc-consensus-babe-rpc = { path = "../../substrate/client/consensus/babe/rpc" }
sc-consensus-beefy = { path = "../../substrate/client/consensus/beefy" }
sc-consensus-beefy-rpc = { path = "../../substrate/client/consensus/beefy/rpc" }
sc-consensus-epochs = { path = "../../substrate/client/consensus/epochs" }
sc-consensus-grandpa = { path = "../../substrate/client/consensus/grandpa" }
sc-consensus-grandpa-rpc = { path = "../../substrate/client/consensus/grandpa/rpc" }
sc-sync-state-rpc = { path = "../../substrate/client/sync-state-rpc" }
txpool-api = { package = "sc-transaction-pool-api", path = "../../substrate/client/transaction-pool/api" }
frame-rpc-system = { package = "substrate-frame-rpc-system", path = "../../substrate/utils/frame/rpc/system" }
mmr-rpc = { path = "../../substrate/client/merkle-mountain-range/rpc" }
pallet-transaction-payment-rpc = { path = "../../substrate/frame/transaction-payment/rpc" }
sp-block-builder = { path = "../../substrate/primitives/block-builder" }
substrate-state-trie-migration-rpc = { path = "../../substrate/utils/frame/rpc/state-trie-migration-rpc" }

[features]
runtime-benchmarks = [
	"frame-rpc-system/runtime-benchmarks",
	"mmr-rpc/runtime-benchmarks",
	"pallet-transaction-payment-rpc/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sc-chain-spec/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus-babe-rpc/runtime-benchmarks",
	"sc-consensus-babe/runtime-benchmarks",
	"sc-consensus-beefy-rpc/runtime-benchmarks",
	"sc-consensus-beefy/runtime-benchmarks",
	"sc-consensus-epochs/runtime-benchmarks",
	"sc-consensus-grandpa-rpc/runtime-benchmarks",
	"sc-consensus-grandpa/runtime-benchmarks",
	"sc-rpc/runtime-benchmarks",
	"sc-sync-state-rpc/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"substrate-state-trie-migration-rpc/runtime-benchmarks",
	"txpool-api/runtime-benchmarks",
]
