[package]
name = "polkadot-rpc"
version = "3.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-rpc"

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["server"] }
polkadot-primitives = { version = "=3.0.0-dev.1", path = "../primitives" }
sc-client-api = { version = "=24.0.0-dev.1", path = "../../substrate/client/api" }
sp-blockchain = { version = "=24.0.0-dev.1", path = "../../substrate/primitives/blockchain" }
sp-keystore = { version = "=0.30.0-dev.1", path = "../../substrate/primitives/keystore" }
sp-runtime = { version = "=27.0.0-dev.1", path = "../../substrate/primitives/runtime" }
sp-api = { version = "=22.0.0-dev.1", path = "../../substrate/primitives/api" }
sp-consensus = { version = "=0.28.0-dev.1", path = "../../substrate/primitives/consensus/common" }
sp-consensus-babe = { version = "=0.28.0-dev.1", path = "../../substrate/primitives/consensus/babe" }
sc-chain-spec = { version = "=23.0.0-dev.1", path = "../../substrate/client/chain-spec" }
sc-rpc = { version = "=25.0.0-dev.1", path = "../../substrate/client/rpc" }
sc-consensus-babe = { version = "=0.30.0-dev.1", path = "../../substrate/client/consensus/babe" }
sc-consensus-babe-rpc = { version = "=0.30.0-dev.1", path = "../../substrate/client/consensus/babe/rpc" }
sc-consensus-beefy = { version = "=9.0.0-dev.1", path = "../../substrate/client/consensus/beefy" }
sc-consensus-beefy-rpc = { version = "=9.0.0-dev.1", path = "../../substrate/client/consensus/beefy/rpc" }
sc-consensus-epochs = { version = "=0.29.0-dev.1", path = "../../substrate/client/consensus/epochs" }
sc-consensus-grandpa = { version = "=0.15.0-dev.1", path = "../../substrate/client/consensus/grandpa" }
sc-consensus-grandpa-rpc = { version = "=0.15.0-dev.1", path = "../../substrate/client/consensus/grandpa/rpc" }
sc-sync-state-rpc = { version = "=0.30.0-dev.1", path = "../../substrate/client/sync-state-rpc" }
txpool-api = { package = "sc-transaction-pool-api", path = "../../substrate/client/transaction-pool/api", version = "=24.0.0-dev.1" }
frame-rpc-system = { package = "substrate-frame-rpc-system", path = "../../substrate/utils/frame/rpc/system", version = "=24.0.0-dev.1" }
mmr-rpc = { version = "=24.0.0-dev.1", path = "../../substrate/client/merkle-mountain-range/rpc" }
pallet-transaction-payment-rpc = { version = "=26.0.0-dev.1", path = "../../substrate/frame/transaction-payment/rpc" }
sp-block-builder = { version = "=22.0.0-dev.1", path = "../../substrate/primitives/block-builder" }
substrate-state-trie-migration-rpc = { version = "=23.0.0-dev.1", path = "../../substrate/utils/frame/rpc/state-trie-migration-rpc" }
