[package]
name = "asset-hub-westend-integration-tests"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Asset Hub Westend runtime integration tests with xcm-emulator"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }
assert_matches = "1.5.0"

# Substrate
sp-runtime = { path = "../../../../../../substrate/primitives/runtime", default-features = false, version = "27.0.0" }
frame-support = { path = "../../../../../../substrate/frame/support", default-features = false, version = "24.0.0" }
frame-system = { path = "../../../../../../substrate/frame/system", default-features = false, version = "24.0.0" }
pallet-balances = { path = "../../../../../../substrate/frame/balances", default-features = false, version = "24.0.0" }
pallet-assets = { path = "../../../../../../substrate/frame/assets", default-features = false, version = "25.0.0" }
pallet-asset-conversion = { path = "../../../../../../substrate/frame/asset-conversion", default-features = false, version = "6.0.0" }

# Polkadot
polkadot-core-primitives = { path = "../../../../../../polkadot/core-primitives", default-features = false, version = "3.0.0" }
polkadot-parachain-primitives = { path = "../../../../../../polkadot/parachain", default-features = false, version = "2.0.0" }
polkadot-runtime-parachains = { version = "3.0.0", path = "../../../../../../polkadot/runtime/parachains" }
polkadot-runtime = { version = "3.0.0", path = "../../../../../../polkadot/runtime/polkadot" }
xcm = { package = "staging-xcm", path = "../../../../../../polkadot/xcm", default-features = false, version = "3.0.0" }
pallet-xcm = { path = "../../../../../../polkadot/xcm/pallet-xcm", default-features = false, version = "3.0.0" }
parachains-common = { version = "3.0.0", path = "../../../../common" }
asset-hub-westend-runtime = { version = "0.11.0", path = "../../../../runtimes/assets/asset-hub-westend" }

# Local
xcm-emulator = { path = "../../../../../xcm/xcm-emulator", default-features = false, version = "0.1.0" }
integration-tests-common = { path = "../../common", default-features = false, version = "0.1.0" }

[features]
runtime-benchmarks = [
	"asset-hub-westend-runtime/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"integration-tests-common/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"polkadot-runtime/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
