[package]
name = "sp-proof-size-ext"
version = "4.0.0-dev"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "A crate which contains an externalities extension to fetch the proof size."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-externalities = { path = "../externalities", default-features = false}
sp-trie = { path = "../trie", default-features = false}
sp-runtime = { path = "../runtime", default-features = false}

[features]
default = ["std"]
std = [
	"sp-externalities/std",
	"sp-trie/std",
	"sp-runtime/std",
]
