[package]
name = "polkadot-statement-table"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-statement-table"

[dependencies]
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
sp-core = { version = "23.0.0", path = "../../substrate/primitives/core" }
primitives = { package = "polkadot-primitives", path = "../primitives", version = "2.0.0" }
