[package]
authors.workspace = true
name = "cumulus-relay-chain-inprocess-interface"
version = "0.1.0"
edition.workspace = true

[dependencies]
async-trait = "0.1.73"
futures = "0.3.28"
futures-timer = "3.0.2"

# Substrate
sc-cli = { path = "../../../substrate/client/cli" }
sc-client-api = { path = "../../../substrate/client/api" }
sc-telemetry = { path = "../../../substrate/client/telemetry" }
sc-tracing = { path = "../../../substrate/client/tracing" }
sc-sysinfo = { path = "../../../substrate/client/sysinfo" }
sp-api = { path = "../../../substrate/primitives/api" }
sp-consensus = { path = "../../../substrate/primitives/consensus/common" }
sp-core = { path = "../../../substrate/primitives/core" }
sp-runtime = { path = "../../../substrate/primitives/runtime" }
sp-state-machine = { path = "../../../substrate/primitives/state-machine" }

# Polkadot
polkadot-cli = { path = "../../../polkadot/cli", default-features = false, features = ["cli"] }
polkadot-service = { path = "../../../polkadot/node/service" }

# Cumulus
cumulus-primitives-core = { path = "../../primitives/core" }
cumulus-relay-chain-interface = { path = "../relay-chain-interface" }

[dev-dependencies]

# Substrate
sp-keyring = { path = "../../../substrate/primitives/keyring" }

# Polkadot
polkadot-primitives = { path = "../../../polkadot/primitives" }
polkadot-test-client = { path = "../../../polkadot/node/test/client" }
metered = { package = "prioritized-metered-channel", version = "0.2.0" }

# Cumulus
cumulus-test-service = { path = "../../test/service" }

[features]
network-protocol-staging = [ "polkadot-service/network-protocol-staging" ]
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"cumulus-relay-chain-interface/runtime-benchmarks",
	"cumulus-test-service/runtime-benchmarks",
	"polkadot-cli/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-service/runtime-benchmarks",
	"polkadot-test-client/runtime-benchmarks",
	"sc-cli/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-sysinfo/runtime-benchmarks",
	"sc-telemetry/runtime-benchmarks",
	"sc-tracing/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
]
