[package]
name = "polkadot-node-core-runtime-api"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }
schnellru = "0.2.1"

sp-consensus-babe = { path = "../../../../substrate/primitives/consensus/babe" }

polkadot-primitives = { path = "../../../primitives" }
polkadot-node-metrics = { path = "../../metrics" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-types = { path = "../../subsystem-types" }

[dev-dependencies]
sp-api = { path = "../../../../substrate/primitives/api" }
sp-core = { path = "../../../../substrate/primitives/core" }
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
async-trait = "0.1.57"
futures = { version = "0.3.21", features = ["thread-pool"] }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-node-primitives = { path = "../../primitives" }
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives/test-helpers" }

[features]
runtime-benchmarks = [
	"gum/runtime-benchmarks",
	"polkadot-node-metrics/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-types/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"test-helpers/runtime-benchmarks",
]
