[package]
name = "polkadot-node-core-pvf-common"
description = "Polkadot crate that contains functionality related to PVFs that is shared by the PVF host and the PVF workers."
version = "3.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cpu-time = "1.0.0"
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../../gum", version = "3.0.0" }
libc = "0.2.139"
tokio = { version = "1.24.2", features = ["fs", "process", "io-util"] }

parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
polkadot-parachain-primitives = { version = "2.0.0", path = "../../../../parachain" }
polkadot-primitives = { version = "3.0.0", path = "../../../../primitives" }
sc-executor = { version = "0.28.0", path = "../../../../../substrate/client/executor" }
sc-executor-common = { version = "0.25.0", path = "../../../../../substrate/client/executor/common" }
sc-executor-wasmtime = { version = "0.25.0", path = "../../../../../substrate/client/executor/wasmtime" }
sp-core = { version = "24.0.0", path = "../../../../../substrate/primitives/core" }
sp-externalities = { version = "0.22.0", path = "../../../../../substrate/primitives/externalities" }
sp-io = { version = "26.0.0", path = "../../../../../substrate/primitives/io" }
sp-tracing = { version = "13.0.0", path = "../../../../../substrate/primitives/tracing" }

[target.'cfg(target_os = "linux")'.dependencies]
landlock = "0.2.0"

[dev-dependencies]
assert_matches = "1.4.0"
tempfile = "3.3.0"

[features]
# This feature is used to export test code to other crates without putting it in the production build.
# Also used for building the puppet worker.
test-utils = []
jemalloc-allocator = []
