[package]
name = "frame-benchmarking"
version = "24.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Macro for benchmarking a FRAME runtime."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false }
linregress = { version = "0.5.1", optional = true }
log = { version = "0.4.17", default-features = false }
paste = "1.0"
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.188", optional = true }
frame-support = { path = "../support", default-features = false, version = "=24.0.0-dev.1" }
frame-support-procedural = { path = "../support/procedural", default-features = false, version = "=19.0.0-dev.1" }
frame-system = { path = "../system", default-features = false, version = "=24.0.0-dev.1" }
sp-api = { path = "../../primitives/api", default-features = false, version = "=22.0.0-dev.1" }
sp-application-crypto = { path = "../../primitives/application-crypto", default-features = false, version = "=26.0.0-dev.1" }
sp-core = { path = "../../primitives/core", default-features = false, version = "=24.0.0-dev.1" }
sp-io = { path = "../../primitives/io", default-features = false, version = "=26.0.0-dev.1" }
sp-runtime = { path = "../../primitives/runtime", default-features = false, version = "=27.0.0-dev.1" }
sp-runtime-interface = { path = "../../primitives/runtime-interface", default-features = false, version = "=20.0.0-dev.1" }
sp-std = { path = "../../primitives/std", default-features = false, version = "=11.0.0-dev.1" }
sp-storage = { path = "../../primitives/storage", default-features = false, version = "=16.0.0-dev.1" }
static_assertions = "1.1.0"

[dev-dependencies]
array-bytes = "6.1"
rusty-fork = { version = "0.3.0", default-features = false }
sp-keystore = { path = "../../primitives/keystore" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-support-procedural/std",
	"frame-support/std",
	"frame-system/std",
	"linregress",
	"log/std",
	"scale-info/std",
	"serde",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime-interface/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-storage/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
