[package]
authors.workspace = true
name = "cumulus-relay-chain-minimal-node"
version = "0.2.0"
edition.workspace = true
description = "cumulus-relay-chain-minimal-node"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
polkadot-primitives = { version = "2.0.0", path = "../../../polkadot/primitives" }
polkadot-core-primitives = { version = "2.0.0", path = "../../../polkadot/core-primitives" }
polkadot-overseer = { version = "2.0.0", path = "../../../polkadot/node/overseer" }
polkadot-node-subsystem-util = { version = "2.0.0", path = "../../../polkadot/node/subsystem-util" }
polkadot-node-network-protocol = { version = "2.0.0", path = "../../../polkadot/node/network/protocol" }
polkadot-availability-recovery = { version = "2.0.0", path = "../../../polkadot/node/network/availability-recovery" }
polkadot-collator-protocol = { version = "2.0.0", path = "../../../polkadot/node/network/collator-protocol" }
polkadot-network-bridge = { version = "2.0.0", path = "../../../polkadot/node/network/bridge" }
polkadot-node-collation-generation = { version = "2.0.0", path = "../../../polkadot/node/collation-generation" }
polkadot-node-core-runtime-api = { version = "2.0.0", path = "../../../polkadot/node/core/runtime-api" }
sc-authority-discovery = { version = "0.29.0", path = "../../../substrate/client/authority-discovery" }
sc-network = { version = "0.29.0", path = "../../../substrate/client/network" }
sc-network-common = { version = "0.28.0", path = "../../../substrate/client/network/common" }
sc-service = { version = "0.30.0", path = "../../../substrate/client/service" }
sc-tracing = { version = "23.0.0", path = "../../../substrate/client/tracing" }
sc-utils = { version = "9.0.0", path = "../../../substrate/client/utils" }
sp-api = { version = "21.0.0", path = "../../../substrate/primitives/api" }
sp-consensus-babe = { version = "0.27.0", path = "../../../substrate/primitives/consensus/babe" }
sp-consensus = { version = "0.27.0", path = "../../../substrate/primitives/consensus/common" }
sp-runtime = { version = "26.0.0", path = "../../../substrate/primitives/runtime" }
cumulus-relay-chain-interface = { version = "0.2.0", path = "../relay-chain-interface" }
cumulus-relay-chain-rpc-interface = { version = "0.2.0", path = "../relay-chain-rpc-interface" }
cumulus-primitives-core = { version = "0.2.0", path = "../../primitives/core" }

array-bytes = "6.1"
schnellru = "0.2.1"
tracing = "0.1.37"
async-trait = "0.1.73"
futures = "0.3.28"

[features]
network-protocol-staging = [
	"polkadot-node-network-protocol/network-protocol-staging",
]
