[package]
authors.workspace = true
name = "cumulus-relay-chain-minimal-node"
version = "0.1.0"
edition.workspace = true

[dependencies]
# polkadot deps
polkadot-primitives = { path = "../../../polkadot/primitives" }
polkadot-core-primitives = { path = "../../../polkadot/core-primitives" }
polkadot-overseer = { path = "../../../polkadot/node/overseer" }
polkadot-node-subsystem-util = { path = "../../../polkadot/node/subsystem-util" }
polkadot-node-network-protocol = { path = "../../../polkadot/node/network/protocol" }

polkadot-availability-recovery = { path = "../../../polkadot/node/network/availability-recovery" }
polkadot-collator-protocol = { path = "../../../polkadot/node/network/collator-protocol" }
polkadot-network-bridge = { path = "../../../polkadot/node/network/bridge" }
polkadot-node-collation-generation = { path = "../../../polkadot/node/collation-generation" }
polkadot-node-core-runtime-api = { path = "../../../polkadot/node/core/runtime-api" }

# substrate deps
sc-authority-discovery = { path = "../../../substrate/client/authority-discovery" }
sc-network = { path = "../../../substrate/client/network" }
sc-network-common = { path = "../../../substrate/client/network/common" }
sc-service = { path = "../../../substrate/client/service" }
sc-tracing = { path = "../../../substrate/client/tracing" }
sc-utils = { path = "../../../substrate/client/utils" }
sp-api = { path = "../../../substrate/primitives/api" }
sp-consensus-babe = { path = "../../../substrate/primitives/consensus/babe" }
sp-consensus = { path = "../../../substrate/primitives/consensus/common" }
sp-runtime = { path = "../../../substrate/primitives/runtime" }

# cumulus deps
cumulus-relay-chain-interface = { path = "../relay-chain-interface" }
cumulus-relay-chain-rpc-interface = { path = "../relay-chain-rpc-interface" }
cumulus-primitives-core = { path = "../../primitives/core" }

array-bytes = "6.1"
schnellru = "0.2.1"
tracing = "0.1.37"
async-trait = "0.1.73"
futures = "0.3.28"

[features]
network-protocol-staging = [
	"polkadot-node-network-protocol/network-protocol-staging",
]
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"cumulus-relay-chain-interface/runtime-benchmarks",
	"cumulus-relay-chain-rpc-interface/runtime-benchmarks",
	"polkadot-availability-recovery/runtime-benchmarks",
	"polkadot-collator-protocol/runtime-benchmarks",
	"polkadot-core-primitives/runtime-benchmarks",
	"polkadot-network-bridge/runtime-benchmarks",
	"polkadot-node-collation-generation/runtime-benchmarks",
	"polkadot-node-core-runtime-api/runtime-benchmarks",
	"polkadot-node-network-protocol/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-overseer/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sc-authority-discovery/runtime-benchmarks",
	"sc-network-common/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sc-tracing/runtime-benchmarks",
	"sc-utils/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
