[package]
name = "sc-service"
version = "0.31.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate service. Starts a thread that spins up the network, client, and extrinsic pool. Manages communication between them."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = [ "rocksdb" ]
# The RocksDB feature activates the RocksDB database backend. If it is not activated, and you pass
# a path to a database, an error will be produced at runtime.
rocksdb = [ "sc-client-db/rocksdb" ]
# exposes the client type
test-helpers = []
runtime-benchmarks = [
	"sc-client-db/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["server"] }
thiserror = "1.0.48"
futures = "0.3.21"
rand = "0.8.5"
parking_lot = "0.12.1"
log = "0.4.17"
futures-timer = "3.0.1"
exit-future = "0.2.0"
pin-project = "1.0.12"
serde = "1.0.188"
serde_json = "1.0.107"
sc-keystore = { version = "=21.0.0-dev.1", path = "../keystore" }
sp-runtime = { version = "=27.0.0-dev.1", path = "../../primitives/runtime" }
sp-trie = { version = "=25.0.0-dev.1", path = "../../primitives/trie" }
sp-externalities = { version = "=0.22.0-dev.1", path = "../../primitives/externalities" }
sc-utils = { version = "=10.0.0-dev.1", path = "../utils" }
sp-version = { version = "=25.0.0-dev.1", path = "../../primitives/version" }
sp-blockchain = { version = "=24.0.0-dev.1", path = "../../primitives/blockchain" }
sp-core = { version = "=24.0.0-dev.1", path = "../../primitives/core" }
sp-keystore = { version = "=0.30.0-dev.1", path = "../../primitives/keystore" }
sp-session = { version = "=23.0.0-dev.1", path = "../../primitives/session" }
sp-state-machine = { version = "=0.31.0-dev.1", path = "../../primitives/state-machine" }
sp-consensus = { version = "=0.28.0-dev.1", path = "../../primitives/consensus/common" }
sc-consensus = { version = "=0.29.0-dev.1", path = "../consensus/common" }
sp-storage = { version = "=16.0.0-dev.1", path = "../../primitives/storage" }
sc-network = { version = "=0.30.0-dev.1", path = "../network" }
sc-network-bitswap = { version = "=0.29.0-dev.1", path = "../network/bitswap" }
sc-network-common = { version = "=0.29.0-dev.1", path = "../network/common" }
sc-network-light = { version = "=0.29.0-dev.1", path = "../network/light" }
sc-network-sync = { version = "=0.29.0-dev.1", path = "../network/sync" }
sc-network-transactions = { version = "=0.29.0-dev.1", path = "../network/transactions" }
sc-chain-spec = { version = "=23.0.0-dev.1", path = "../chain-spec" }
sc-client-api = { version = "=24.0.0-dev.1", path = "../api" }
sp-api = { version = "=22.0.0-dev.1", path = "../../primitives/api" }
sc-client-db = { path = "../db", default-features = false, version = "=0.31.0-dev.1" }
codec = { package = "parity-scale-codec", version = "3.6.1" }
sc-executor = { version = "=0.28.0-dev.1", path = "../executor" }
sc-transaction-pool = { version = "=24.0.0-dev.1", path = "../transaction-pool" }
sp-transaction-pool = { version = "=22.0.0-dev.1", path = "../../primitives/transaction-pool" }
sc-transaction-pool-api = { version = "=24.0.0-dev.1", path = "../transaction-pool/api" }
sp-transaction-storage-proof = { version = "=22.0.0-dev.1", path = "../../primitives/transaction-storage-proof" }
sc-rpc-server = { version = "=9.0.0-dev.1", path = "../rpc-servers" }
sc-rpc = { version = "=25.0.0-dev.1", path = "../rpc" }
sc-rpc-spec-v2 = { version = "=0.30.0-dev.1", path = "../rpc-spec-v2" }
sc-block-builder = { version = "=0.29.0-dev.1", path = "../block-builder" }
sc-informant = { version = "=0.29.0-dev.1", path = "../informant" }
sc-telemetry = { version = "=11.0.0-dev.1", path = "../telemetry" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../utils/prometheus", version = "=0.15.0-dev.1" }
sc-tracing = { version = "=24.0.0-dev.1", path = "../tracing" }
sc-sysinfo = { version = "=23.0.0-dev.1", path = "../sysinfo" }
tracing = "0.1.29"
tracing-futures = { version = "0.2.4" }
async-trait = "0.1.57"
tokio = { version = "1.22.0", features = ["time", "rt-multi-thread", "parking_lot"] }
tempfile = "3.1.0"
directories = "5.0.1"
static_init = "1.0.3"

[dev-dependencies]
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
substrate-test-runtime = { path = "../../test-utils/runtime" }
