[package]
name = "polkadot-node-collation-generation"
version = "3.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-node-collation-generation"

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../gum", version = "=3.0.0-dev.1" }
polkadot-erasure-coding = { version = "=3.0.0-dev.1", path = "../../erasure-coding" }
polkadot-node-primitives = { version = "=3.0.0-dev.1", path = "../primitives" }
polkadot-node-subsystem = { version = "=3.0.0-dev.1", path = "../subsystem" }
polkadot-node-subsystem-util = { version = "=3.0.0-dev.1", path = "../subsystem-util" }
polkadot-primitives = { version = "=3.0.0-dev.1", path = "../../primitives" }
sp-core = { version = "=24.0.0-dev.1", path = "../../../substrate/primitives/core" }
sp-maybe-compressed-blob = { version = "=8.0.0-dev.1", path = "../../../substrate/primitives/maybe-compressed-blob" }
thiserror = "1.0.48"
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["bit-vec", "derive"] }

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../primitives/test-helpers" }
assert_matches = "1.4.0"
sp-keyring = { path = "../../../substrate/primitives/keyring" }
