[package]
name = "pallet-nomination-pools-runtime-api"
version = "19.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Runtime API for nomination-pools FRAME pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
sp-api = { path = "../../../primitives/api", default-features = false, version = "=22.0.0-dev.1" }
sp-std = { path = "../../../primitives/std", default-features = false, version = "=11.0.0-dev.1" }
pallet-nomination-pools = { path = "..", default-features = false, version = "=21.0.0-dev.1" }

[features]
default = [ "std" ]
std = [ "codec/std", "pallet-nomination-pools/std", "sp-api/std", "sp-std/std" ]
