[package]
name = "polkadot-parachain-bin"
version = "2.0.0"
authors.workspace = true
build = "build.rs"
edition.workspace = true
description = "Runs a polkadot parachain node which could be a collator."

[[bin]]
name = "polkadot-parachain"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.73"
clap = { version = "4.4.2", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0" }
futures = "0.3.28"
hex-literal = "0.4.1"
log = "0.4.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
rococo-parachain-runtime = { version = "0.1.0", path = "../parachains/runtimes/testing/rococo-parachain" }
shell-runtime = { version = "0.2.0", path = "../parachains/runtimes/starters/shell" }
glutton-runtime = { version = "2.0.0", path = "../parachains/runtimes/glutton/glutton-kusama" }
seedling-runtime = { version = "0.2.0", path = "../parachains/runtimes/starters/seedling" }
asset-hub-polkadot-runtime = { version = "0.10.0", path = "../parachains/runtimes/assets/asset-hub-polkadot" }
asset-hub-kusama-runtime = { version = "0.10.0", path = "../parachains/runtimes/assets/asset-hub-kusama" }
asset-hub-westend-runtime = { version = "0.10.0", path = "../parachains/runtimes/assets/asset-hub-westend" }
collectives-polkadot-runtime = { version = "2.0.0", path = "../parachains/runtimes/collectives/collectives-polkadot" }
contracts-rococo-runtime = { version = "0.3.0", path = "../parachains/runtimes/contracts/contracts-rococo" }
bridge-hub-rococo-runtime = { version = "0.2.0", path = "../parachains/runtimes/bridge-hubs/bridge-hub-rococo" }
bridge-hub-kusama-runtime = { version = "0.2.0", path = "../parachains/runtimes/bridge-hubs/bridge-hub-kusama" }
bridge-hub-polkadot-runtime = { version = "0.2.0", path = "../parachains/runtimes/bridge-hubs/bridge-hub-polkadot" }
penpal-runtime = { version = "0.9.27", path = "../parachains/runtimes/testing/penpal" }
jsonrpsee = { version = "0.16.2", features = ["server"] }
parachains-common = { version = "2.0.0", path = "../parachains/common" }
frame-benchmarking = { version = "23.0.0", path = "../../substrate/frame/benchmarking" }
frame-benchmarking-cli = { version = "27.0.0", path = "../../substrate/utils/frame/benchmarking-cli" }
sp-runtime = { path = "../../substrate/primitives/runtime", default-features = false, version = "26.0.0" }
sp-io = { version = "25.0.0", path = "../../substrate/primitives/io" }
sp-core = { version = "23.0.0", path = "../../substrate/primitives/core" }
sp-session = { version = "22.0.0", path = "../../substrate/primitives/session" }
sc-consensus = { version = "0.28.0", path = "../../substrate/client/consensus/common" }
sc-cli = { version = "0.31.0", path = "../../substrate/client/cli" }
sc-client-api = { version = "23.0.0", path = "../../substrate/client/api" }
sc-executor = { version = "0.27.0", path = "../../substrate/client/executor" }
sc-service = { version = "0.30.0", path = "../../substrate/client/service" }
sc-telemetry = { version = "10.0.0", path = "../../substrate/client/telemetry" }
sc-transaction-pool = { version = "23.0.0", path = "../../substrate/client/transaction-pool" }
sp-transaction-pool = { version = "21.0.0", path = "../../substrate/primitives/transaction-pool" }
sc-network = { version = "0.29.0", path = "../../substrate/client/network" }
sc-network-sync = { version = "0.28.0", path = "../../substrate/client/network/sync" }
sc-basic-authorship = { version = "0.29.0", path = "../../substrate/client/basic-authorship" }
sp-timestamp = { version = "21.0.0", path = "../../substrate/primitives/timestamp" }
sp-blockchain = { version = "23.0.0", path = "../../substrate/primitives/blockchain" }
sp-block-builder = { version = "21.0.0", path = "../../substrate/primitives/block-builder" }
sp-keystore = { version = "0.29.0", path = "../../substrate/primitives/keystore" }
sc-chain-spec = { version = "22.0.0", path = "../../substrate/client/chain-spec" }
sc-rpc = { version = "24.0.0", path = "../../substrate/client/rpc" }
sc-tracing = { version = "23.0.0", path = "../../substrate/client/tracing" }
sp-offchain = { version = "21.0.0", path = "../../substrate/primitives/offchain" }
sp-api = { version = "21.0.0", path = "../../substrate/primitives/api" }
sp-consensus-aura = { version = "0.27.0", path = "../../substrate/primitives/consensus/aura" }
sc-sysinfo = { version = "22.0.0", path = "../../substrate/client/sysinfo" }
substrate-prometheus-endpoint = { version = "0.14.0", path = "../../substrate/utils/prometheus" }
sc-transaction-pool-api = { version = "23.0.0", path = "../../substrate/client/transaction-pool/api" }
frame-rpc-system = { package = "substrate-frame-rpc-system", path = "../../substrate/utils/frame/rpc/system", version = "23.0.0" }
pallet-transaction-payment-rpc = { version = "25.0.0", path = "../../substrate/frame/transaction-payment/rpc" }
substrate-state-trie-migration-rpc = { version = "22.0.0", path = "../../substrate/utils/frame/rpc/state-trie-migration-rpc" }

# Polkadot
# Use rococo-native as this is currently the default "local" relay chain
polkadot-cli = { path = "../../polkadot/cli", features = ["rococo-native"], version = "2.0.0" }
polkadot-primitives = { version = "2.0.0", path = "../../polkadot/primitives" }
polkadot-service = { version = "2.0.0", path = "../../polkadot/node/service" }
xcm = { package = "staging-xcm", path = "../../polkadot/xcm", version = "2.0.0" }
cumulus-client-cli = { version = "0.2.0", path = "../client/cli" }
cumulus-client-collator = { version = "0.2.0", path = "../client/collator" }
cumulus-client-consensus-aura = { version = "0.2.0", path = "../client/consensus/aura" }
cumulus-client-consensus-relay-chain = { version = "0.2.0", path = "../client/consensus/relay-chain" }
cumulus-client-consensus-common = { version = "0.2.0", path = "../client/consensus/common" }
cumulus-client-consensus-proposer = { version = "0.2.0", path = "../client/consensus/proposer" }
cumulus-client-service = { version = "0.2.0", path = "../client/service" }
cumulus-primitives-core = { version = "0.2.0", path = "../primitives/core" }
cumulus-primitives-parachain-inherent = { version = "0.2.0", path = "../primitives/parachain-inherent" }
cumulus-relay-chain-interface = { version = "0.2.0", path = "../client/relay-chain-interface" }
color-print = "0.3.4"

[build-dependencies]
substrate-build-script-utils = { version = "7.0.0", path = "../../substrate/utils/build-script-utils" }

[dev-dependencies]
assert_cmd = "2.0"
nix = { version = "0.26.1", features = ["signal"] }
tempfile = "3.8.0"
tokio = { version = "1.32.0", features = ["macros", "time", "parking_lot"] }
wait-timeout = "0.2"

[features]
default = []
runtime-benchmarks = [
	"asset-hub-kusama-runtime/runtime-benchmarks",
	"asset-hub-polkadot-runtime/runtime-benchmarks",
	"asset-hub-westend-runtime/runtime-benchmarks",
	"bridge-hub-kusama-runtime/runtime-benchmarks",
	"bridge-hub-polkadot-runtime/runtime-benchmarks",
	"bridge-hub-rococo-runtime/runtime-benchmarks",
	"collectives-polkadot-runtime/runtime-benchmarks",
	"contracts-rococo-runtime/runtime-benchmarks",
	"frame-benchmarking-cli/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"glutton-runtime/runtime-benchmarks",
	"penpal-runtime/runtime-benchmarks",
	"polkadot-cli/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-service/runtime-benchmarks",
	"rococo-parachain-runtime/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"asset-hub-kusama-runtime/try-runtime",
	"asset-hub-polkadot-runtime/try-runtime",
	"asset-hub-westend-runtime/try-runtime",
	"bridge-hub-kusama-runtime/try-runtime",
	"bridge-hub-polkadot-runtime/try-runtime",
	"bridge-hub-rococo-runtime/try-runtime",
	"collectives-polkadot-runtime/try-runtime",
	"contracts-rococo-runtime/try-runtime",
	"glutton-runtime/try-runtime",
	"penpal-runtime/try-runtime",
	"polkadot-cli/try-runtime",
	"polkadot-service/try-runtime",
	"shell-runtime/try-runtime",
	"sp-runtime/try-runtime",
]
