[package]
name = "polkadot-primitives-test-helpers"
publish = false
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-primitives-test-helpers"

[dependencies]
sp-keyring = { version = "27.0.0", path = "../../../substrate/primitives/keyring" }
sp-application-crypto = { package = "sp-application-crypto", path = "../../../substrate/primitives/application-crypto", default-features = false, version = "26.0.0" }
sp-runtime = { version = "27.0.0", path = "../../../substrate/primitives/runtime" }
sp-core = { path = "../../../substrate/primitives/core", features = ["std"], version = "24.0.0" }
polkadot-primitives = { version = "3.0.0", path = ".." }
rand = "0.8.5"
