[package]
name = "sp-rpc"
version = "22.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate RPC primitives and utilities."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
rustc-hash = "1.1.0"
serde = { version = "1.0.188", features = ["derive"] }
sp-core = { version = "=24.0.0-dev.1", path = "../core" }

[dev-dependencies]
serde_json = "1.0.107"
