[package]
name = "bp-wococo"
description = "Primitives of Wococo runtime."
version = "0.2.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]

# Bridge Dependencies

bp-header-chain = { path = "../header-chain", default-features = false, version = "=0.3.0-dev.1" }
bp-polkadot-core = { path = "../polkadot-core", default-features = false, version = "=0.3.0-dev.1" }
bp-runtime = { path = "../runtime", default-features = false, version = "=0.3.0-dev.1" }
bp-rococo = { path = "../chain-rococo", default-features = false, version = "=0.2.0-dev.1" }

# Substrate Based Dependencies

frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "=24.0.0-dev.1" }
sp-api = { path = "../../../substrate/primitives/api", default-features = false, version = "=22.0.0-dev.1" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "=11.0.0-dev.1" }

[features]
default = [ "std" ]
std = [
	"bp-header-chain/std",
	"bp-polkadot-core/std",
	"bp-rococo/std",
	"bp-runtime/std",
	"frame-support/std",
	"sp-api/std",
	"sp-std/std",
]
