[package]
name = "polkadot-core-primitives"
version = "3.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-core-primitives"

[dependencies]
sp-core = { path = "../../substrate/primitives/core", default-features = false, version = "=24.0.0-dev.1" }
sp-std = { path = "../../substrate/primitives/std", default-features = false, version = "=11.0.0-dev.1" }
sp-runtime = { path = "../../substrate/primitives/runtime", default-features = false, version = "=27.0.0-dev.1" }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
parity-scale-codec = { version = "3.6.1", default-features = false, features = [ "derive" ] }

[features]
default = [ "std" ]
std = [
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
