[package]
name = "bp-relayers"
description = "Primitives of relayers module."
version = "0.2.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false, features = ["derive", "bit-vec"] }
scale-info = { version = "2.9.0", default-features = false, features = ["bit-vec", "derive"] }

# Bridge Dependencies

bp-messages = { path = "../messages", default-features = false, version = "0.2.0" }
bp-runtime = { path = "../runtime", default-features = false, version = "0.2.0" }

# Substrate Dependencies

frame-support = { path = "../../../../substrate/frame/support", default-features = false, version = "23.0.0" }
sp-runtime = { path = "../../../../substrate/primitives/runtime", default-features = false, version = "26.0.0" }
sp-std = { path = "../../../../substrate/primitives/std", default-features = false, version = "10.0.0" }

[dev-dependencies]
hex = "0.4"
hex-literal = "0.4"

[features]
default = [ "std" ]
std = [
	"bp-messages/std",
	"bp-runtime/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-std/std",
]
