[package]
name = "sp-proof-size-hostfunction"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"

[dependencies]
sp-runtime-interface = { path = "../runtime-interface", default-features = false }
sp-externalities = { path = "../externalities", default-features = false }
sp-trie = { path = "../trie", default-features = false }

[dev-dependencies]
sp-state-machine = { path = "../state-machine" }
sp-core = { path = "../core" }
sp-io = { path = "../io" }

[features]
default = [ "std" ]
std = [ "sp-externalities/std", "sp-runtime-interface/std", "sp-trie/std" ]
