[package]
name = "cumulus-primitives-utility"
version = "0.3.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "cumulus-primitives-utility"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [ "derive" ] }
log = { version = "0.4.20", default-features = false }

# Substrate
frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "=24.0.0-dev.1" }
sp-io = { path = "../../../substrate/primitives/io", default-features = false, version = "=26.0.0-dev.1" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "=27.0.0-dev.1" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "=11.0.0-dev.1" }

# Polkadot
polkadot-runtime-common = { path = "../../../polkadot/runtime/common", default-features = false, version = "=3.0.0-dev.1" }
xcm = { package = "staging-xcm", path = "../../../polkadot/xcm", default-features = false, version = "=3.0.0-dev.1" }
xcm-executor = { package = "staging-xcm-executor", path = "../../../polkadot/xcm/xcm-executor", default-features = false, version = "=3.0.0-dev.1" }
xcm-builder = { package = "staging-xcm-builder", path = "../../../polkadot/xcm/xcm-builder", default-features = false, version = "=3.0.0-dev.1" }


# Cumulus
cumulus-primitives-core = { path = "../core", default-features = false, version = "=0.3.0-dev.1" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"polkadot-runtime-common/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]

runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
