[package]
name = "polkadot-voter-bags"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.4.1", features = ["derive"] }

generate-bags = { path = "../../../substrate/utils/frame/generate-bags" }
sp-io = { path = "../../../substrate/primitives/io" }

westend-runtime = { path = "../../runtime/westend" }
kusama-runtime = { package = "staging-kusama-runtime", path = "../../runtime/kusama" }
polkadot-runtime = { path = "../../runtime/polkadot" }

[features]
runtime-benchmarks = [
	"generate-bags/runtime-benchmarks",
	"kusama-runtime/runtime-benchmarks",
	"polkadot-runtime/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"westend-runtime/runtime-benchmarks",
]
