[package]
name = "polkadot-voter-bags"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-voter-bags"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
generate-bags = { version = "23.0.0", path = "../../../substrate/utils/frame/generate-bags" }
sp-io = { version = "25.0.0", path = "../../../substrate/primitives/io" }
westend-runtime = { version = "2.0.0", path = "../../runtime/westend" }
kusama-runtime = { package = "staging-kusama-runtime", path = "../../runtime/kusama", version = "2.0.0" }
polkadot-runtime = { version = "2.0.0", path = "../../runtime/polkadot" }
