[package]
name = "polkadot-node-subsystem-test-helpers"
description = "Subsystem traits and message definitions"
publish = false
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1.57"
futures = "0.3.21"
parking_lot = "0.12.0"
polkadot-node-subsystem = { version = "2.0.0", path = "../subsystem" }
polkadot-node-subsystem-util = { version = "2.0.0", path = "../subsystem-util" }
polkadot-primitives = { version = "2.0.0", path = "../../primitives" }
sp-core = { version = "23.0.0", path = "../../../substrate/primitives/core" }
sp-keystore = { version = "0.29.0", path = "../../../substrate/primitives/keystore" }
sc-keystore = { version = "20.0.0", path = "../../../substrate/client/keystore" }
sp-keyring = { version = "26.0.0", path = "../../../substrate/primitives/keyring" }
sp-application-crypto = { version = "25.0.0", path = "../../../substrate/primitives/application-crypto" }

[dev-dependencies]
polkadot-overseer = { path = "../overseer" }
