[package]
name = "frame-benchmarking-cli"
version = "28.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "CLI for benchmarking FRAME"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = "6.1"
chrono = "0.4"
clap = { version = "4.4.4", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.6.1" }
comfy-table = { version = "7.0.1", default-features = false }
handlebars = "4.2.2"
Inflector = "0.11.4"
itertools = "0.10.3"
lazy_static = "1.4.0"
linked-hash-map = "0.5.4"
log = "0.4.17"
rand = { version = "0.8.4", features = ["small_rng"] }
rand_pcg = "0.3.1"
serde = "1.0.188"
serde_json = "1.0.107"
thiserror = "1.0.48"
thousands = "0.2.0"
frame-benchmarking = { version = "=24.0.0-dev.1", path = "../../../frame/benchmarking" }
frame-support = { version = "=24.0.0-dev.1", path = "../../../frame/support" }
frame-system = { version = "=24.0.0-dev.1", path = "../../../frame/system" }
sc-block-builder = { version = "=0.29.0-dev.1", path = "../../../client/block-builder" }
sc-cli = { path = "../../../client/cli", default-features = false, version = "=0.32.0-dev.1" }
sc-client-api = { version = "=24.0.0-dev.1", path = "../../../client/api" }
sc-client-db = { path = "../../../client/db", default-features = false, version = "=0.31.0-dev.1" }
sc-executor = { version = "=0.28.0-dev.1", path = "../../../client/executor" }
sc-service = { path = "../../../client/service", default-features = false, version = "=0.31.0-dev.1" }
sc-sysinfo = { version = "=23.0.0-dev.1", path = "../../../client/sysinfo" }
sp-api = { version = "=22.0.0-dev.1", path = "../../../primitives/api" }
sp-blockchain = { version = "=24.0.0-dev.1", path = "../../../primitives/blockchain" }
sp-core = { version = "=24.0.0-dev.1", path = "../../../primitives/core" }
sp-database = { version = "=8.0.0-dev.1", path = "../../../primitives/database" }
sp-externalities = { version = "=0.22.0-dev.1", path = "../../../primitives/externalities" }
sp-inherents = { version = "=22.0.0-dev.1", path = "../../../primitives/inherents" }
sp-keystore = { version = "=0.30.0-dev.1", path = "../../../primitives/keystore" }
sp-runtime = { version = "=27.0.0-dev.1", path = "../../../primitives/runtime" }
sp-state-machine = { version = "=0.31.0-dev.1", path = "../../../primitives/state-machine" }
sp-storage = { version = "=16.0.0-dev.1", path = "../../../primitives/storage" }
sp-trie = { version = "=25.0.0-dev.1", path = "../../../primitives/trie" }
sp-io = { version = "=26.0.0-dev.1", path = "../../../primitives/io" }
sp-wasm-interface = { version = "=17.0.0-dev.1", path = "../../../primitives/wasm-interface" }
gethostname = "0.2.3"

[features]
default = [ "rocksdb" ]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sc-client-db/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
rocksdb = [ "sc-cli/rocksdb", "sc-client-db/rocksdb" ]
