[package]
name = "bp-xcm-bridge-hub-router"
description = "Primitives of the xcm-bridge-hub fee pallet."
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false, features = ["derive", "bit-vec"] }
scale-info = { version = "2.9.0", default-features = false, features = ["bit-vec", "derive"] }

# Substrate Dependencies
sp-runtime = { path = "../../../../substrate/primitives/runtime", default-features = false, version = "26.0.0" }
sp-core = { path = "../../../../substrate/primitives/core", default-features = false, version = "23.0.0" }

[features]
default = [ "std" ]
std = [ "codec/std", "scale-info/std", "sp-core/std", "sp-runtime/std" ]
