[package]
name = "cumulus-client-consensus-relay-chain"
description = "The relay-chain provided consensus algorithm"
version = "0.2.0"
authors.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.73"
futures = "0.3.28"
parking_lot = "0.12.1"
tracing = "0.1.37"
sc-consensus = { version = "0.28.0", path = "../../../../substrate/client/consensus/common" }
sp-api = { version = "21.0.0", path = "../../../../substrate/primitives/api" }
sp-block-builder = { version = "21.0.0", path = "../../../../substrate/primitives/block-builder" }
sp-blockchain = { version = "23.0.0", path = "../../../../substrate/primitives/blockchain" }
sp-consensus = { version = "0.27.0", path = "../../../../substrate/primitives/consensus/common" }
sp-core = { version = "23.0.0", path = "../../../../substrate/primitives/core" }
sp-inherents = { version = "21.0.0", path = "../../../../substrate/primitives/inherents" }
sp-runtime = { version = "26.0.0", path = "../../../../substrate/primitives/runtime" }
substrate-prometheus-endpoint = { version = "0.14.0", path = "../../../../substrate/utils/prometheus" }
cumulus-client-consensus-common = { version = "0.2.0", path = "../common" }
cumulus-primitives-core = { version = "0.2.0", path = "../../../primitives/core" }
cumulus-relay-chain-interface = { version = "0.2.0", path = "../../relay-chain-interface" }
