[package]
authors.workspace = true
edition.workspace = true
name = "staging-parachain-info"
version = "0.3.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "parachain-info"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

frame-support = { path = "../../../../substrate/frame/support", default-features = false, version = "24.0.0" }
frame-system = { path = "../../../../substrate/frame/system", default-features = false, version = "24.0.0" }

sp-runtime = { path = "../../../../substrate/primitives/runtime", default-features = false, version = "27.0.0" }
sp-std = { path = "../../../../substrate/primitives/std", default-features = false, version = "11.0.0" }

cumulus-primitives-core = { path = "../../../primitives/core", default-features = false, version = "0.3.0" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
