[package]
name = "polkadot-dispute-distribution"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../../gum" }
derive_more = "0.99.17"
parity-scale-codec = { version = "3.6.1", features = ["std"] }
polkadot-primitives = { path = "../../../primitives" }
polkadot-erasure-coding = { path = "../../../erasure-coding" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-network-protocol = { path = "../protocol" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-primitives = { path = "../../primitives" }
sc-network = { path = "../../../../substrate/client/network" }
sp-application-crypto = { path = "../../../../substrate/primitives/application-crypto" }
sp-keystore = { path = "../../../../substrate/primitives/keystore" }
thiserror = "1.0.31"
fatality = "0.0.6"
schnellru = "0.2.1"
indexmap = "1.9.1"

[dev-dependencies]
async-channel = "1.8.0"
async-trait = "0.1.57"
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
sp-tracing = { path = "../../../../substrate/primitives/tracing" }
sc-keystore = { path = "../../../../substrate/client/keystore" }
futures-timer = "3.0.2"
assert_matches = "1.4.0"
lazy_static = "1.4.0"
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }

[features]
runtime-benchmarks = [
	"gum/runtime-benchmarks",
	"polkadot-erasure-coding/runtime-benchmarks",
	"polkadot-node-network-protocol/runtime-benchmarks",
	"polkadot-node-primitives/runtime-benchmarks",
	"polkadot-node-subsystem-test-helpers/runtime-benchmarks",
	"polkadot-node-subsystem-util/runtime-benchmarks",
	"polkadot-node-subsystem/runtime-benchmarks",
	"polkadot-primitives-test-helpers/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sc-keystore/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks",
]
