[package]
name = "sp-inherents"
version = "22.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Provides types and traits for creating and checking inherents."
documentation = "https://docs.rs/sp-inherents"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.57", optional = true }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
impl-trait-for-tuples = "0.2.2"
thiserror = { version = "1.0.48", optional = true }
sp-runtime = { path = "../runtime", default-features = false, optional = true, version = "=27.0.0-dev.1" }
sp-std = { path = "../std", default-features = false, version = "=11.0.0-dev.1" }

[dev-dependencies]
futures = "0.3.21"

[features]
default = [ "std" ]
std = [
	"async-trait",
	"codec/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
	"thiserror",
]
