[package]
name = "cumulus-primitives-core"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "cumulus-primitives-core"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [ "derive" ] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

# Substrate
sp-api = { path = "../../../substrate/primitives/api", default-features = false, version = "22.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "27.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "11.0.0" }
sp-trie = { path = "../../../substrate/primitives/trie", default-features = false, version = "25.0.0" }

# Polkadot
polkadot-core-primitives = { path = "../../../polkadot/core-primitives", default-features = false, version = "3.0.0" }
polkadot-parachain-primitives = { path = "../../../polkadot/parachain", default-features = false, version = "2.0.0" }
polkadot-primitives = { path = "../../../polkadot/primitives", default-features = false, version = "3.0.0" }
xcm = { package = "staging-xcm", path = "../../../polkadot/xcm", default-features = false, version = "3.0.1" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"polkadot-core-primitives/std",
	"polkadot-parachain-primitives/std",
	"polkadot-primitives/std",
	"scale-info/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-trie/std",
	"xcm/std",
]
