[package]
name = "xcm-emulator"
description = "Test kit to emulate XCM program execution."
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
paste = "1.0.14"
log = { version = "0.4.20", default-features = false }
lazy_static = "1.4.0"
impl-trait-for-tuples = "0.2.2"

# Substrate
frame-support = { path = "../../../substrate/frame/support" }
frame-system = { path = "../../../substrate/frame/system" }
sp-io = { path = "../../../substrate/primitives/io" }
sp-core = { path = "../../../substrate/primitives/core" }
sp-std = { path = "../../../substrate/primitives/std" }
sp-runtime = { path = "../../../substrate/primitives/runtime" }
sp-arithmetic = { path = "../../../substrate/primitives/arithmetic" }
sp-trie = { path = "../../../substrate/primitives/trie" }
pallet-balances = { path = "../../../substrate/frame/balances" }
pallet-message-queue = { path = "../../../substrate/frame/message-queue" }

# Cumulus
cumulus-primitives-core = { path = "../../primitives/core" }
cumulus-pallet-xcmp-queue = { path = "../../pallets/xcmp-queue" }
cumulus-pallet-dmp-queue = { path = "../../pallets/dmp-queue" }
cumulus-pallet-parachain-system = { path = "../../pallets/parachain-system" }
parachain-info = { path = "../../parachains/pallets/parachain-info" }
cumulus-primitives-parachain-inherent = { path = "../../primitives/parachain-inherent" }
cumulus-test-relay-sproof-builder = { path = "../../test/relay-sproof-builder" }
parachains-common = { path = "../../parachains/common" }

# Polkadot
xcm = { package = "staging-xcm", path = "../../../polkadot/xcm" }
xcm-executor = { package = "staging-xcm-executor", path = "../../../polkadot/xcm/xcm-executor" }
polkadot-primitives = { path = "../../../polkadot/primitives" }
polkadot-runtime-parachains = { path = "../../../polkadot/runtime/parachains" }

[features]
runtime-benchmarks = [
	"cumulus-pallet-dmp-queue/runtime-benchmarks",
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"cumulus-primitives-parachain-inherent/runtime-benchmarks",
	"cumulus-test-relay-sproof-builder/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"parachain-info/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"sp-arithmetic/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-io/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-trie/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"xcm/runtime-benchmarks",
]
