[package]
name = "pallet-aura"
version = "4.0.0-dev"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME AURA consensus pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive", "max-encoded-len"] }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
frame-support = { path = "../support", default-features = false}
frame-system = { path = "../system", default-features = false}
pallet-authorship = { path = "../authorship", default-features = false, optional = true }
pallet-session = { path = "../session", default-features = false, optional = true }
pallet-timestamp = { path = "../timestamp", default-features = false }
sp-application-crypto = { path = "../../primitives/application-crypto", default-features = false}
sp-consensus-aura = { path = "../../primitives/consensus/aura", default-features = false}
sp-runtime = { path = "../../primitives/runtime", default-features = false}
sp-session = { path = "../../primitives/session", default-features = false}
sp-staking = { path = "../../primitives/staking", default-features = false, features = ["serde"]}
sp-std = { path = "../../primitives/std", default-features = false}

[dev-dependencies]
sp-core = { path = "../../primitives/core", default-features = false}
sp-io = { path = "../../primitives/io" }
pallet-authorship = { path = "../authorship" }
pallet-session = { path = "../session" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-authorship/std",
	"pallet-timestamp/std",
	"scale-info/std",
	"sp-application-crypto/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-timestamp/try-runtime",
	"sp-runtime/try-runtime",
]
default-equivocation-report-system = [
	"pallet-authorship",
	"pallet-session",
]
experimental = []
