[package]
name = "cumulus-client-service"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
description = "cumulus-client-service"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
futures = "0.3.28"
sc-client-api = { version = "23.0.0", path = "../../../substrate/client/api" }
sc-consensus = { version = "0.28.0", path = "../../../substrate/client/consensus/common" }
sc-transaction-pool = { version = "23.0.0", path = "../../../substrate/client/transaction-pool" }
sc-rpc = { version = "24.0.0", path = "../../../substrate/client/rpc" }
sc-service = { version = "0.30.0", path = "../../../substrate/client/service" }
sc-sysinfo = { version = "22.0.0", path = "../../../substrate/client/sysinfo" }
sc-telemetry = { version = "10.0.0", path = "../../../substrate/client/telemetry" }
sc-network = { version = "0.29.0", path = "../../../substrate/client/network" }
sc-network-sync = { version = "0.28.0", path = "../../../substrate/client/network/sync" }
sc-utils = { version = "9.0.0", path = "../../../substrate/client/utils" }
sc-network-transactions = { version = "0.28.0", path = "../../../substrate/client/network/transactions" }
sp-api = { version = "21.0.0", path = "../../../substrate/primitives/api" }
sp-blockchain = { version = "23.0.0", path = "../../../substrate/primitives/blockchain" }
sp-consensus = { version = "0.27.0", path = "../../../substrate/primitives/consensus/common" }
sp-core = { version = "23.0.0", path = "../../../substrate/primitives/core" }
sp-runtime = { version = "26.0.0", path = "../../../substrate/primitives/runtime" }
sp-transaction-pool = { version = "21.0.0", path = "../../../substrate/primitives/transaction-pool" }
polkadot-primitives = { version = "2.0.0", path = "../../../polkadot/primitives" }
cumulus-client-cli = { version = "0.2.0", path = "../cli" }
cumulus-client-collator = { version = "0.2.0", path = "../collator" }
cumulus-client-consensus-common = { version = "0.2.0", path = "../consensus/common" }
cumulus-client-pov-recovery = { version = "0.2.0", path = "../pov-recovery" }
cumulus-client-network = { version = "0.2.0", path = "../network" }
cumulus-primitives-core = { version = "0.2.0", path = "../../primitives/core" }
cumulus-relay-chain-interface = { version = "0.2.0", path = "../relay-chain-interface" }
cumulus-relay-chain-inprocess-interface = { version = "0.2.0", path = "../relay-chain-inprocess-interface" }
cumulus-relay-chain-minimal-node = { version = "0.2.0", path = "../relay-chain-minimal-node" }

[features]
network-protocol-staging = [
	"cumulus-relay-chain-inprocess-interface/network-protocol-staging",
	"cumulus-relay-chain-minimal-node/network-protocol-staging",
]
