[package]
name = "polkadot-overseer"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-overseer"

[dependencies]
client = { package = "sc-client-api", path = "../../../substrate/client/api", version = "23.0.0" }
sp-api = { version = "21.0.0", path = "../../../substrate/primitives/api" }
futures = "0.3.21"
futures-timer = "3.0.2"
parking_lot = "0.12.0"
polkadot-node-network-protocol = { version = "2.0.0", path = "../network/protocol" }
polkadot-node-primitives = { version = "2.0.0", path = "../primitives" }
polkadot-node-subsystem-types = { version = "2.0.0", path = "../subsystem-types" }
polkadot-node-metrics = { version = "2.0.0", path = "../metrics" }
polkadot-primitives = { version = "2.0.0", path = "../../primitives" }
orchestra = "0.0.5"
gum = { package = "tracing-gum", path = "../gum", version = "2.0.0" }
schnellru = "0.2.1"
sp-core = { version = "23.0.0", path = "../../../substrate/primitives/core" }
async-trait = "0.1.57"
tikv-jemalloc-ctl = { version = "0.5.0", optional = true }

[dev-dependencies]
metered = { package = "prioritized-metered-channel", version = "0.2.0" }
sp-core = { path = "../../../substrate/primitives/core" }
futures = { version = "0.3.21", features = ["thread-pool"] }
femme = "2.2.1"
assert_matches = "1.4.0"
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../primitives/test-helpers" }

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemalloc-ctl = "0.5.0"

[features]
default = []
expand = [ "orchestra/expand" ]
dotgraph = [ "orchestra/dotgraph" ]
jemalloc-allocator = [ "dep:tikv-jemalloc-ctl" ]
