[package]
name = "polkadot-node-core-provisioner"
version = "3.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-node-core-provisioner"

[dependencies]
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum", version = "=3.0.0-dev.1" }
thiserror = "1.0.48"
polkadot-primitives = { version = "=3.0.0-dev.1", path = "../../../primitives" }
polkadot-node-primitives = { version = "=3.0.0-dev.1", path = "../../primitives" }
polkadot-node-subsystem = { version = "=3.0.0-dev.1", path = "../../subsystem" }
polkadot-node-subsystem-util = { version = "=3.0.0-dev.1", path = "../../subsystem-util" }
futures-timer = "3.0.2"
fatality = "0.0.6"

[dev-dependencies]
sp-application-crypto = { path = "../../../../substrate/primitives/application-crypto" }
sp-keystore = { path = "../../../../substrate/primitives/keystore" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives/test-helpers" }
