[package]
name = "cumulus-client-consensus-proposer"
description = "A Substrate `Proposer` for building parachain blocks"
version = "0.2.0"
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
async-trait = "0.1.73"
thiserror = "1.0.48"
sp-consensus = { version = "0.27.0", path = "../../../../substrate/primitives/consensus/common" }
sp-inherents = { version = "21.0.0", path = "../../../../substrate/primitives/inherents" }
sp-runtime = { version = "26.0.0", path = "../../../../substrate/primitives/runtime" }
sp-state-machine = { version = "0.30.0", path = "../../../../substrate/primitives/state-machine" }
cumulus-primitives-parachain-inherent = { version = "0.2.0", path = "../../../primitives/parachain-inherent" }
