[package]
name = "cumulus-client-consensus-proposer"
description = "A Substrate `Proposer` for building parachain blocks"
version = "0.3.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.73"
thiserror = "1.0.48"
sp-consensus = { version = "=0.28.0-dev.1", path = "../../../../substrate/primitives/consensus/common" }
sp-inherents = { version = "=22.0.0-dev.1", path = "../../../../substrate/primitives/inherents" }
sp-runtime = { version = "=27.0.0-dev.1", path = "../../../../substrate/primitives/runtime" }
sp-state-machine = { version = "=0.31.0-dev.1", path = "../../../../substrate/primitives/state-machine" }
cumulus-primitives-parachain-inherent = { version = "=0.3.0-dev.1", path = "../../../primitives/parachain-inherent" }
