[package]
name = "sc-consensus-aura"
version = "0.10.0-dev"
authors.workspace = true
description = "Aura consensus algorithm for substrate"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.57"
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.21"
log = "0.4.17"
thiserror = "1.0"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus" }
sc-block-builder = { path = "../../block-builder" }
sc-client-api = { path = "../../api" }
sc-consensus = { path = "../common" }
sc-consensus-slots = { path = "../slots" }
sc-telemetry = { path = "../../telemetry" }
sp-api = { path = "../../../primitives/api" }
sp-application-crypto = { path = "../../../primitives/application-crypto" }
sp-block-builder = { path = "../../../primitives/block-builder" }
sp-blockchain = { path = "../../../primitives/blockchain" }
sp-consensus = { path = "../../../primitives/consensus/common" }
sp-consensus-aura = { path = "../../../primitives/consensus/aura" }
sp-consensus-slots = { path = "../../../primitives/consensus/slots" }
sp-core = { path = "../../../primitives/core" }
sp-inherents = { path = "../../../primitives/inherents" }
sp-keystore = { path = "../../../primitives/keystore" }
sp-runtime = { path = "../../../primitives/runtime" }

[dev-dependencies]
parking_lot = "0.12.1"
tempfile = "3.1.0"
sc-keystore = { path = "../../keystore" }
sc-network = { path = "../../network" }
sc-network-test = { path = "../../network/test" }
sp-keyring = { path = "../../../primitives/keyring" }
sp-timestamp = { path = "../../../primitives/timestamp" }
sp-tracing = { path = "../../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }
tokio = { version = "1.22.0" }

[features]
runtime-benchmarks = [
	"sc-block-builder/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus-slots/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-keystore/runtime-benchmarks",
	"sc-network-test/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sc-telemetry/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-application-crypto/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus-aura/runtime-benchmarks",
	"sp-consensus-slots/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-keystore/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-timestamp/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
]
