[package]
name = "sc-consensus-aura"
version = "0.30.0-dev.1"
authors.workspace = true
description = "Aura consensus algorithm for substrate"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.57"
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.21"
log = "0.4.17"
thiserror = "1.0"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus", version = "=0.15.0-dev.1" }
sc-block-builder = { version = "=0.29.0-dev.1", path = "../../block-builder" }
sc-client-api = { version = "=24.0.0-dev.1", path = "../../api" }
sc-consensus = { version = "=0.29.0-dev.1", path = "../common" }
sc-consensus-slots = { version = "=0.29.0-dev.1", path = "../slots" }
sc-telemetry = { version = "=11.0.0-dev.1", path = "../../telemetry" }
sp-api = { version = "=22.0.0-dev.1", path = "../../../primitives/api" }
sp-application-crypto = { version = "=26.0.0-dev.1", path = "../../../primitives/application-crypto" }
sp-block-builder = { version = "=22.0.0-dev.1", path = "../../../primitives/block-builder" }
sp-blockchain = { version = "=24.0.0-dev.1", path = "../../../primitives/blockchain" }
sp-consensus = { version = "=0.28.0-dev.1", path = "../../../primitives/consensus/common" }
sp-consensus-aura = { version = "=0.28.0-dev.1", path = "../../../primitives/consensus/aura" }
sp-consensus-slots = { version = "=0.28.0-dev.1", path = "../../../primitives/consensus/slots" }
sp-core = { version = "=24.0.0-dev.1", path = "../../../primitives/core" }
sp-inherents = { version = "=22.0.0-dev.1", path = "../../../primitives/inherents" }
sp-keystore = { version = "=0.30.0-dev.1", path = "../../../primitives/keystore" }
sp-runtime = { version = "=27.0.0-dev.1", path = "../../../primitives/runtime" }

[dev-dependencies]
parking_lot = "0.12.1"
tempfile = "3.1.0"
sc-keystore = { path = "../../keystore" }
sc-network = { path = "../../network" }
sc-network-test = { path = "../../network/test" }
sp-keyring = { path = "../../../primitives/keyring" }
sp-timestamp = { path = "../../../primitives/timestamp" }
sp-tracing = { path = "../../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }
tokio = { version = "1.22.0" }
