[package]
name = "seedling-runtime"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
description = "seedling-runtime"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }

# Substrate
frame-executive = { path = "../../../../../substrate/frame/executive", default-features = false, version = "23.0.0" }
frame-support = { path = "../../../../../substrate/frame/support", default-features = false, version = "23.0.0" }
frame-system = { path = "../../../../../substrate/frame/system", default-features = false, version = "23.0.0" }
pallet-balances = { path = "../../../../../substrate/frame/balances", default-features = false, version = "23.0.0" }
pallet-sudo = { path = "../../../../../substrate/frame/sudo", default-features = false, version = "23.0.0" }
sp-api = { path = "../../../../../substrate/primitives/api", default-features = false, version = "21.0.0" }
sp-block-builder = { path = "../../../../../substrate/primitives/block-builder", default-features = false, version = "21.0.0" }
sp-core = { path = "../../../../../substrate/primitives/core", default-features = false, version = "23.0.0" }
sp-inherents = { path = "../../../../../substrate/primitives/inherents", default-features = false, version = "21.0.0" }
sp-offchain = { path = "../../../../../substrate/primitives/offchain", default-features = false, version = "21.0.0" }
sp-runtime = { path = "../../../../../substrate/primitives/runtime", default-features = false, version = "26.0.0" }
sp-session = { path = "../../../../../substrate/primitives/session", default-features = false, version = "22.0.0" }
sp-std = { path = "../../../../../substrate/primitives/std", default-features = false, version = "10.0.0" }
sp-transaction-pool = { path = "../../../../../substrate/primitives/transaction-pool", default-features = false, version = "21.0.0" }
sp-version = { path = "../../../../../substrate/primitives/version", default-features = false, version = "24.0.0" }

# Cumulus
cumulus-pallet-parachain-system = { path = "../../../../pallets/parachain-system", default-features = false, features = ["parameterized-consensus-hook"], version = "0.2.0" }
cumulus-pallet-solo-to-para = { path = "../../../../pallets/solo-to-para", default-features = false, version = "0.2.0" }
parachain-info = { package = "staging-parachain-info", path = "../../../pallets/parachain-info", default-features = false, version = "0.2.0" }
parachains-common = { path = "../../../common", default-features = false, version = "2.0.0" }
cumulus-primitives-core = { path = "../../../../primitives/core", default-features = false, version = "0.2.0" }

[build-dependencies]
substrate-wasm-builder = { path = "../../../../../substrate/utils/wasm-builder", optional = true, version = "12.0.0" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-solo-to-para/std",
	"cumulus-primitives-core/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-sudo/std",
	"parachain-info/std",
	"parachains-common/std",
	"scale-info/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"substrate-wasm-builder",
]
