[package]
name = "remote-ext-tests-bags-list"
publish = false
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "remote-ext-tests-bags-list"

[dependencies]
polkadot-runtime = { version = "3.0.0", path = "../../../runtime/polkadot" }
kusama-runtime = { package = "staging-kusama-runtime", path = "../../../runtime/kusama", version = "3.0.0" }
westend-runtime = { version = "3.0.0", path = "../../../runtime/westend" }
polkadot-runtime-constants = { version = "3.0.0", path = "../../../runtime/polkadot/constants" }
kusama-runtime-constants = { version = "3.0.0", path = "../../../runtime/kusama/constants" }
westend-runtime-constants = { version = "3.0.0", path = "../../../runtime/westend/constants" }
pallet-bags-list-remote-tests = { version = "0.1.0", path = "../../../../substrate/frame/bags-list/remote-tests" }
sp-tracing = { version = "13.0.0", path = "../../../../substrate/primitives/tracing" }
frame-system = { version = "24.0.0", path = "../../../../substrate/frame/system" }
sp-core = { version = "24.0.0", path = "../../../../substrate/primitives/core" }

clap = { version = "4.4.4", features = ["derive"] }
log = "0.4.17"
tokio = { version = "1.24.2", features = ["macros"] }
