[package]
name = "remote-ext-tests-bags-list"
publish = false
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
polkadot-runtime = { path = "../../../runtime/polkadot" }
kusama-runtime = { package = "staging-kusama-runtime", path = "../../../runtime/kusama" }
westend-runtime = { path = "../../../runtime/westend" }
polkadot-runtime-constants = { path = "../../../runtime/polkadot/constants" }
kusama-runtime-constants = { path = "../../../runtime/kusama/constants" }
westend-runtime-constants = { path = "../../../runtime/westend/constants" }

pallet-bags-list-remote-tests = { path = "../../../../substrate/frame/bags-list/remote-tests" }
sp-tracing = { path = "../../../../substrate/primitives/tracing" }
frame-system = { path = "../../../../substrate/frame/system" }
sp-core = { path = "../../../../substrate/primitives/core" }

clap = { version = "4.4.1", features = ["derive"] }
log = "0.4.17"
tokio = { version = "1.24.2", features = ["macros"] }

[features]
runtime-benchmarks = [
	"frame-system/runtime-benchmarks",
	"kusama-runtime-constants/runtime-benchmarks",
	"kusama-runtime/runtime-benchmarks",
	"pallet-bags-list-remote-tests/runtime-benchmarks",
	"polkadot-runtime-constants/runtime-benchmarks",
	"polkadot-runtime/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"westend-runtime-constants/runtime-benchmarks",
	"westend-runtime/runtime-benchmarks",
]
