[package]
name = "polkadot-cli"
description = "Polkadot Relay-chain Client Node"
version = "3.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on Linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = { version = "4.4.4", features = ["derive"], optional = true }
log = "0.4.17"
thiserror = "1.0.48"
futures = "0.3.21"
pyro = { package = "pyroscope", version = "0.5.3", optional = true }
pyroscope_pprofrs = { version = "0.2", optional = true }

service = { package = "polkadot-service", path = "../node/service", default-features = false, optional = true, version = "=3.0.0-dev.1" }
polkadot-performance-test = { path = "../node/test/performance-test", optional = true, version = "=3.0.0-dev.1" }
sp-core = { version = "=24.0.0-dev.1", path = "../../substrate/primitives/core" }
sp-io = { version = "=26.0.0-dev.1", path = "../../substrate/primitives/io" }
sp-keyring = { version = "=27.0.0-dev.1", path = "../../substrate/primitives/keyring" }
sp-maybe-compressed-blob = { version = "=8.0.0-dev.1", path = "../../substrate/primitives/maybe-compressed-blob" }
frame-benchmarking-cli = { path = "../../substrate/utils/frame/benchmarking-cli", optional = true, version = "=28.0.0-dev.1" }
try-runtime-cli = { path = "../../substrate/utils/frame/try-runtime/cli", optional = true, version = "=0.34.0-dev.1" }
sc-cli = { path = "../../substrate/client/cli", optional = true, version = "=0.32.0-dev.1" }
sc-service = { path = "../../substrate/client/service", optional = true, version = "=0.31.0-dev.1" }
polkadot-node-metrics = { version = "=3.0.0-dev.1", path = "../node/metrics" }
sc-tracing = { path = "../../substrate/client/tracing", optional = true, version = "=24.0.0-dev.1" }
sc-sysinfo = { version = "=23.0.0-dev.1", path = "../../substrate/client/sysinfo" }
sc-executor = { version = "=0.28.0-dev.1", path = "../../substrate/client/executor" }
sc-storage-monitor = { version = "=0.12.0-dev.1", path = "../../substrate/client/storage-monitor" }

[build-dependencies]
substrate-build-script-utils = { version = "=8.0.0-dev.1", path = "../../substrate/utils/build-script-utils" }

[features]
default = [ "cli", "db", "full-node" ]
db = [ "service/db" ]
cli = [
	"clap",
	"frame-benchmarking-cli",
	"sc-cli",
	"sc-service",
	"sc-tracing",
	"service",
	"try-runtime-cli",
]
runtime-benchmarks = [
	"frame-benchmarking-cli?/runtime-benchmarks",
	"polkadot-node-metrics/runtime-benchmarks",
	"polkadot-performance-test?/runtime-benchmarks",
	"sc-service?/runtime-benchmarks",
	"service/runtime-benchmarks",
]
full-node = [ "service/full-node" ]
try-runtime = [ "service/try-runtime", "try-runtime-cli/try-runtime" ]
fast-runtime = [ "service/fast-runtime" ]
pyroscope = [ "pyro", "pyroscope_pprofrs" ]
hostperfcheck = [ "polkadot-performance-test" ]

# Configure the native runtimes to use.
westend-native = [ "service/westend-native" ]
rococo-native = [ "service/rococo-native" ]

malus = [ "full-node", "service/malus" ]
runtime-metrics = [
	"polkadot-node-metrics/runtime-metrics",
	"service/runtime-metrics",
]
