[package]
name = "pallet-collective-content"
version = "0.2.0-dev.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Managed content"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { version = "2.3.0", default-features = false, features = ["derive"] }

frame-benchmarking = { path = "../../../../substrate/frame/benchmarking", optional = true, default-features = false, version = "=24.0.0-dev.1" }
frame-support = { path = "../../../../substrate/frame/support", default-features = false, version = "=24.0.0-dev.1" }
frame-system = { path = "../../../../substrate/frame/system", default-features = false, version = "=24.0.0-dev.1" }

sp-core = { path = "../../../../substrate/primitives/core", default-features = false, version = "=24.0.0-dev.1" }
sp-runtime = { path = "../../../../substrate/primitives/runtime", default-features = false, version = "=27.0.0-dev.1" }
sp-std = { path = "../../../../substrate/primitives/std", default-features = false, version = "=11.0.0-dev.1" }

[dev-dependencies]
sp-io = { path = "../../../../substrate/primitives/io", default-features = false }

[features]
default = [ "std" ]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]

try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]

std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
