[package]
name = "polkadot-node-core-pvf-prepare-worker"
description = "Polkadot crate that contains the logic for preparing PVFs. Used by the polkadot-prepare-worker binary."
version = "3.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../../gum", version = "=3.0.0-dev.1" }
libc = "0.2.139"
rayon = "1.5.1"
tikv-jemalloc-ctl = { version = "0.5.0", optional = true }
tokio = { version = "1.24.2", features = ["fs", "process"] }

parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
polkadot-node-core-pvf-common = { version = "=3.0.0-dev.1", path = "../common" }
polkadot-parachain-primitives = { version = "=2.0.0-dev.1", path = "../../../../parachain" }
polkadot-primitives = { version = "=3.0.0-dev.1", path = "../../../../primitives" }
sc-executor = { version = "=0.28.0-dev.1", path = "../../../../../substrate/client/executor" }
sc-executor-common = { version = "=0.25.0-dev.1", path = "../../../../../substrate/client/executor/common" }
sc-executor-wasmtime = { version = "=0.25.0-dev.1", path = "../../../../../substrate/client/executor/wasmtime" }
sp-io = { version = "=26.0.0-dev.1", path = "../../../../../substrate/primitives/io" }
sp-maybe-compressed-blob = { version = "=8.0.0-dev.1", path = "../../../../../substrate/primitives/maybe-compressed-blob" }
sp-tracing = { version = "=13.0.0-dev.1", path = "../../../../../substrate/primitives/tracing" }

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemalloc-ctl = "0.5.0"

[features]
builder = []
jemalloc-allocator = [
	"dep:tikv-jemalloc-ctl",
	"polkadot-node-core-pvf-common/jemalloc-allocator",
]
