[package]
name = "frame-election-provider-solution-type"
version = "11.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "NPoS Solution Type"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.37", features = ["full", "visit"] }
quote = "1.0.28"
proc-macro2 = "1.0.56"
proc-macro-crate = "1.1.3"

[dev-dependencies]
parity-scale-codec = "3.6.1"
scale-info = "2.1.1"
sp-arithmetic = { path = "../../../primitives/arithmetic" }
frame-election-provider-support = { path = ".." }
frame-support = { path = "../../support" }
trybuild = "1.0.74"
