[package]
name = "staging-xcm-executor"
description = "An abstract and configurable XCM message executor."
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "2.0.0"

[dependencies]
impl-trait-for-tuples = "0.2.2"
environmental = { version = "1.1.4", default-features = false }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
xcm = { package = "staging-xcm", path = "..", default-features = false, version = "2.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "10.0.0" }
sp-io = { path = "../../../substrate/primitives/io", default-features = false, version = "25.0.0" }
sp-arithmetic = { path = "../../../substrate/primitives/arithmetic", default-features = false, version = "18.0.0" }
sp-core = { path = "../../../substrate/primitives/core", default-features = false, version = "23.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "26.0.0" }
sp-weights = { path = "../../../substrate/primitives/weights", default-features = false, version = "22.0.0" }
frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "23.0.0" }
log = { version = "0.4.17", default-features = false }
frame-benchmarking = { path = "../../../substrate/frame/benchmarking", default-features = false, optional = true, version = "23.0.0" }

[features]
default = [ "std" ]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
std = [
	"frame-benchmarking/std",
	"frame-support/std",
	"log/std",
	"parity-scale-codec/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-weights/std",
	"xcm/std",
]
