[package]
name = "substrate-frame-cli"
version = "28.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "cli interface for FRAME"
documentation = "https://docs.rs/substrate-frame-cli"
readme = "README.md"

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
frame-support = { version = "=24.0.0-dev.1", path = "../../../frame/support" }
frame-system = { version = "=24.0.0-dev.1", path = "../../../frame/system" }
sc-cli = { version = "=0.32.0-dev.1", path = "../../../client/cli" }
sp-core = { version = "=24.0.0-dev.1", path = "../../../primitives/core" }
sp-runtime = { version = "=27.0.0-dev.1", path = "../../../primitives/runtime" }

[features]
default = []
