[package]
name = "pallet-nfts-runtime-api"
version = "10.0.0-dev.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Runtime API for the FRAME NFTs pallet."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
pallet-nfts = { path = "..", default-features = false, version = "=18.0.0-dev.1" }
sp-api = { path = "../../../primitives/api", default-features = false, version = "=22.0.0-dev.1" }

[features]
default = [ "std" ]
std = [ "codec/std", "pallet-nfts/std", "sp-api/std" ]
