[package]
name = "sc-consensus-slots"
version = "0.10.0-dev"
authors.workspace = true
description = "Generic slots-based utilities for consensus"
edition.workspace = true
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.57"
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.21"
futures-timer = "3.0.1"
log = "0.4.17"
sc-client-api = { path = "../../api" }
sc-consensus = { path = "../common" }
sc-telemetry = { path = "../../telemetry" }
sp-arithmetic = { path = "../../../primitives/arithmetic" }
sp-blockchain = { path = "../../../primitives/blockchain" }
sp-consensus = { path = "../../../primitives/consensus/common" }
sp-consensus-slots = { path = "../../../primitives/consensus/slots" }
sp-core = { path = "../../../primitives/core" }
sp-inherents = { path = "../../../primitives/inherents" }
sp-runtime = { path = "../../../primitives/runtime" }
sp-state-machine = { path = "../../../primitives/state-machine" }

[dev-dependencies]
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }

[features]
runtime-benchmarks = [
	"sc-client-api/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-telemetry/runtime-benchmarks",
	"sp-arithmetic/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus-slots/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"substrate-test-runtime-client/runtime-benchmarks",
]
