[package]
name = "sc-consensus-slots"
version = "0.29.0-dev.1"
authors.workspace = true
description = "Generic slots-based utilities for consensus"
edition.workspace = true
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.57"
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.21"
futures-timer = "3.0.1"
log = "0.4.17"
sc-client-api = { version = "=24.0.0-dev.1", path = "../../api" }
sc-consensus = { version = "=0.29.0-dev.1", path = "../common" }
sc-telemetry = { version = "=11.0.0-dev.1", path = "../../telemetry" }
sp-arithmetic = { version = "=19.0.0-dev.1", path = "../../../primitives/arithmetic" }
sp-blockchain = { version = "=24.0.0-dev.1", path = "../../../primitives/blockchain" }
sp-consensus = { version = "=0.28.0-dev.1", path = "../../../primitives/consensus/common" }
sp-consensus-slots = { version = "=0.28.0-dev.1", path = "../../../primitives/consensus/slots" }
sp-core = { version = "=24.0.0-dev.1", path = "../../../primitives/core" }
sp-inherents = { version = "=22.0.0-dev.1", path = "../../../primitives/inherents" }
sp-runtime = { version = "=27.0.0-dev.1", path = "../../../primitives/runtime" }
sp-state-machine = { version = "=0.31.0-dev.1", path = "../../../primitives/state-machine" }

[dev-dependencies]
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }
