[package]
name = "cumulus-primitives-reclaim"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
sp-runtime-interface = { path = "../../../substrate/primitives/runtime-interface", default-features = false }

[features]
default = ["std"]
std = [
	"sp-runtime-interface/std",
]
