[package]
name = "cumulus-primitives-reclaim"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
sp-runtime-interface = { path = "../../../substrate/primitives/runtime-interface", default-features = false }
sp-externalities = { path = "../../../substrate/primitives/externalities", default-features = false }
sp-proof-size-ext = { path = "../../../substrate/primitives/proof-size-ext", optional = true }

[dev-dependencies]
sp-state-machine = { path = "../../../substrate/primitives/state-machine" }
sp-trie = { path = "../../../substrate/primitives/trie" }
sp-core = { path = "../../../substrate/primitives/core" }
sp-io = { path = "../../../substrate/primitives/io" }

[features]
default = [ "std" ]
std = [
	"sp-externalities/std",
	"sp-proof-size-ext",
	"sp-runtime-interface/std",
]
