[package]
name = "rococo-parachain-runtime"
version = "0.2.0-dev.1"
authors.workspace = true
edition.workspace = true
description = "Simple runtime used by the rococo parachain(s)"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }

# Substrate
frame-benchmarking = { path = "../../../../../substrate/frame/benchmarking", default-features = false, optional = true, version = "=24.0.0-dev.1" }
frame-executive = { path = "../../../../../substrate/frame/executive", default-features = false, version = "=24.0.0-dev.1" }
frame-support = { path = "../../../../../substrate/frame/support", default-features = false, version = "=24.0.0-dev.1" }
frame-system = { path = "../../../../../substrate/frame/system", default-features = false, version = "=24.0.0-dev.1" }
frame-system-rpc-runtime-api = { path = "../../../../../substrate/frame/system/rpc/runtime-api", default-features = false, version = "=22.0.0-dev.1" }
pallet-assets = { path = "../../../../../substrate/frame/assets", default-features = false, version = "=25.0.0-dev.1" }
pallet-aura = { path = "../../../../../substrate/frame/aura", default-features = false, version = "=23.0.0-dev.1" }
pallet-balances = { path = "../../../../../substrate/frame/balances", default-features = false, version = "=24.0.0-dev.1" }
pallet-sudo = { path = "../../../../../substrate/frame/sudo", default-features = false, version = "=24.0.0-dev.1" }
pallet-timestamp = { path = "../../../../../substrate/frame/timestamp", default-features = false, version = "=23.0.0-dev.1" }
pallet-transaction-payment = { path = "../../../../../substrate/frame/transaction-payment", default-features = false, version = "=24.0.0-dev.1" }
pallet-transaction-payment-rpc-runtime-api = { path = "../../../../../substrate/frame/transaction-payment/rpc/runtime-api", default-features = false, version = "=24.0.0-dev.1" }
sp-api = { path = "../../../../../substrate/primitives/api", default-features = false, version = "=22.0.0-dev.1" }
sp-block-builder = { path = "../../../../../substrate/primitives/block-builder", default-features = false, version = "=22.0.0-dev.1" }
sp-consensus-aura = { path = "../../../../../substrate/primitives/consensus/aura", default-features = false, version = "=0.28.0-dev.1" }
sp-core = { path = "../../../../../substrate/primitives/core", default-features = false, version = "=24.0.0-dev.1" }
sp-genesis-builder = { path = "../../../../../substrate/primitives/genesis-builder", default-features = false, version = "=0.3.0-dev.1" }
sp-inherents = { path = "../../../../../substrate/primitives/inherents", default-features = false, version = "=22.0.0-dev.1" }
sp-offchain = { path = "../../../../../substrate/primitives/offchain", default-features = false, version = "=22.0.0-dev.1" }
sp-runtime = { path = "../../../../../substrate/primitives/runtime", default-features = false, version = "=27.0.0-dev.1" }
sp-session = { path = "../../../../../substrate/primitives/session", default-features = false, version = "=23.0.0-dev.1" }
sp-std = { path = "../../../../../substrate/primitives/std", default-features = false, version = "=11.0.0-dev.1" }
sp-transaction-pool = { path = "../../../../../substrate/primitives/transaction-pool", default-features = false, version = "=22.0.0-dev.1" }
sp-version = { path = "../../../../../substrate/primitives/version", default-features = false, version = "=25.0.0-dev.1" }

# Polkadot
pallet-xcm = { path = "../../../../../polkadot/xcm/pallet-xcm", default-features = false, version = "=3.0.0-dev.1" }
polkadot-parachain-primitives = { path = "../../../../../polkadot/parachain", default-features = false, version = "=2.0.0-dev.1" }
xcm = { package = "staging-xcm", path = "../../../../../polkadot/xcm", default-features = false, version = "=3.0.0-dev.1" }
xcm-builder = { package = "staging-xcm-builder", path = "../../../../../polkadot/xcm/xcm-builder", default-features = false, version = "=3.0.0-dev.1" }
xcm-executor = { package = "staging-xcm-executor", path = "../../../../../polkadot/xcm/xcm-executor", default-features = false, version = "=3.0.0-dev.1" }

# Cumulus
cumulus-pallet-aura-ext = { path = "../../../../pallets/aura-ext", default-features = false, version = "=0.3.0-dev.1" }
cumulus-pallet-dmp-queue = { path = "../../../../pallets/dmp-queue", default-features = false, version = "=0.3.0-dev.1" }
cumulus-pallet-parachain-system = { path = "../../../../pallets/parachain-system", default-features = false, features = ["parameterized-consensus-hook"], version = "=0.3.0-dev.1" }
cumulus-pallet-xcm = { path = "../../../../pallets/xcm", default-features = false, version = "=0.3.0-dev.1" }
cumulus-pallet-xcmp-queue = { path = "../../../../pallets/xcmp-queue", default-features = false, version = "=0.3.0-dev.1" }
cumulus-ping = { path = "../../../pallets/ping", default-features = false, version = "=0.3.0-dev.1" }
cumulus-primitives-core = { path = "../../../../primitives/core", default-features = false, version = "=0.3.0-dev.1" }
cumulus-primitives-utility = { path = "../../../../primitives/utility", default-features = false, version = "=0.3.0-dev.1" }
parachains-common = { path = "../../../common", default-features = false, version = "=3.0.0-dev.1" }
parachain-info = { package = "staging-parachain-info", path = "../../../pallets/parachain-info", default-features = false, version = "=0.3.0-dev.1" }

[build-dependencies]
substrate-wasm-builder = { path = "../../../../../substrate/utils/wasm-builder", optional = true, version = "=13.0.0-dev.1" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"cumulus-pallet-aura-ext/std",
	"cumulus-pallet-dmp-queue/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcm/std",
	"cumulus-pallet-xcmp-queue/std",
	"cumulus-ping/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-utility/std",
	"frame-benchmarking?/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-assets/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-xcm/std",
	"parachain-info/std",
	"parachains-common/std",
	"polkadot-parachain-primitives/std",
	"scale-info/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"substrate-wasm-builder",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]
runtime-benchmarks = [
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"cumulus-primitives-utility/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]

experimental = [ "pallet-aura/experimental" ]
